### ISSUE TITLE
.htaccess Error 500 in Apache 2.4 because of FilterProvider

### ISSUE THREAD

**Issue by bchr** [h5bp/html5-boilerplate#1012]
From http://httpd.apache.org/docs/2.4/upgrading.html:

> mod_filter: FilterProvider syntax has changed and now uses a boolean expression to determine if a filter is applied.

From http://httpd.apache.org/docs/2.4/mod/mod_filter.html:

> The FilterProvider directive has changed from httpd 2.2: the match and dispatch arguments are replaced with a single but more versatile expression. In general, you can convert a match/dispatch pair to the two sides of an expression [...].

**Comment by fropky** [comment]
> I've got a more compact code for apache 2.4:
> 
> ```
> # HTML, TXT, CSS, JavaScript, JSON, XML, HTC:
> <IfModule filter_module>
>     FilterDeclare  COMPRESS
>     FilterProvider COMPRESS DEFLATE "%{CONTENT_TYPE} =~ m#^text/(html|css|plain|xml|x-component)#i"
>     FilterProvider COMPRESS DEFLATE "%{CONTENT_TYPE} =~ m#^application/(javascript|json|xml|xhtml+xml|rss+xml|atom+xml|vnd.ms-fontobject|x-font-ttf)#i"
>     FilterProvider COMPRESS DEFLATE "%{CONTENT_TYPE} =~ m#^image/(svg+xml|x-icon)#i"
>     FilterProvider COMPRESS DEFLATE "%{CONTENT_TYPE} = 'font/opentype'"
>     FilterChain    COMPRESS
>     FilterProtocol COMPRESS DEFLATE change=yes;byteranges=no
> </IfModule>
> ```

This method is not working for me for Apache 2.4/wordpress installation. Html is not compressing. Other file like js and css is compressed. Any suggestions?
