### ISSUE TITLE
.htaccess option to use SymLinksIfOwnerMatch instead of FollowSymLinks

### ISSUE THREAD

**Issue by ghost** [h5bp/html5-boilerplate#1147]
Recently my web host decided to disallow the use of the `FollowSymLinks` option in hostees .htaccess files, and suggests to use `SymLinksIfOwnerMatch` instead (see [this note on their website](https://krystal.info/index.php?/News/NewsItem/View/9/security-measure-symlinks) for more details). I have implemented the change in my own files and it appears to work fine with my own mod_rewrite rules.

To preempt this scenario for other users, I suggest a commented-out option to select `SymLinksIfOwnerMatch` instead of `FollowSymLinks` be included in the HTML5BP .htaccess file. The latter would be the default for the moment, and the code would look something like this (this includes an explanatory comment):

```
# If using the h5bp in a subdirectory, use `RewriteBase /foo` instead where 'foo' is your directory.
# If your web host doesn't allow the FollowSymlinks option, comment it out and use `Options +SymLinksOfOwnerMatch`

<IfModule mod_rewrite.c>
  Options +FollowSymlinks
# Options +SymLinksIfOwnerMatch
  RewriteEngine On
# RewriteBase /
</IfModule>
```

The default functionality of .htaccess would remain the same of course, but the option to change it is made available for those who require it. However, I understand that the limited .htaccess mod-rewrite functionality in my own sites may not provide an adequate test as to whether enabling this option will cause other unseen issues, so wider testing might be advantageous.

**Comment by clicktv** [comment]
thank you
