### ISSUE TITLE
Sticky Footer

### ISSUE THREAD

**Issue by iurikothe** [h5bp/html5-boilerplate#117]
I've found a Sticky footer (using jQuery) that works fine on OSX's Chrome/Firefox/Safari (at least).
CSS stickies seem to be better (read that on css tricks), but this is really simple.
Just add this jQuery code:

```
positionFooter(); 
  function positionFooter(){
    if($(document.body).height() < $(window).height()){
      $("footer").css({position: "absolute",top:($(window).scrollTop()+$(window).height()-$("footer").height())+"px"})
    }
  }
  $(window)
    .scroll(positionFooter)
    .resize(positionFooter)
```

inspired by: http://www.hardcode.nl/archives_139/article_244-jquery-sticky-footer

what do you think?
could someone try it on IEs?

should this be default to Boilerplate?
any better option? (CSS version?)

**Comment by dandv** [comment]
Flexbox makes sticky footer trivial. I filed #1718 for adding flexbox support after discontinuing IE8.
