### ISSUE TITLE
Remove @page at rule from print styles

### ISSUE THREAD

**Issue by keeganstreet** [h5bp/html5-boilerplate#1408]
When the @page at-rule is included in the print styles, and the page is printed in Chrome, the headers (Date, Title) and footers (URL, Page Number) are not printed, even when the "headers and footers" checkbox is selected.

Test case: http://jsbin.com/aripet/1

Chrome Version 28.0.1500.71
Mac OS 10.7.5

I will need to open a ticket at Chrome too and link it here as I think this is actually a bug in Chrome not H5BP.

**Comment by alessandroloverde** [comment]
It does not seem a bug to me. If you set margins to 0 in @page, your headers and footers won't be printed. They require margins in the page, by whatever mean you want

**Comment by roblarsen** [comment]
This issue was closed 9 years ago. Has something changed?

**Comment by alessandroloverde** [comment]
> This issue was closed 9 years ago. Has something changed?

I just think that wasn't a bug from the beginning; just a misunderstood feature. I got into that page because I was searching infos on the topic so I thought a clarification would have been helpful for future readers.
