### ISSUE TITLE
Revise the `lang` attribute problem

### ISSUE THREAD

**Issue by alrra** [h5bp/html5-boilerplate#1542]
### Problem Overview

Developers often forgot to change the value of the `lang` attribute, so we decided to [remove it from `<html>`](https://github.com/h5bp/html5-boilerplate/issues/1110).

The change isn't quite good enough as some users:
- won't read the docs, and thus, they will find the absence of `lang` attribute confusing, or won't even know that they should be adding it
- won't even notice the absence of the `lang`  attribute, and thus will forget to add it anyway (maybe expecting it to be there)
### Specification and Browsers

From http://www.whatwg.org/specs/web-apps/current-work/multipage/elements.html#attr-lang:

> To determine the language of a node, user agents must look at the nearest ancestor element (including the element itself if the node is an element) that has a lang attribute in the XML namespace set or is an HTML element and has a lang in no namespace attribute set. That attribute specifies the language of the node (regardless of its value).
> 
> If both the lang attribute in no namespace and the lang attribute in the XML namespace are set on an element, user agents must use the lang attribute in the XML namespace, and the lang attribute in no namespace must be ignored for the purposes of determining the element's language.
> 
> If neither the node nor any of the node's ancestors, including the root element, have either attribute set, but there is a pragma-set default language set, then that is the language of the node. If there is no pragma-set default language set, then language information from a higher-level protocol (such as HTTP), if any, must be used as the final fallback language instead. In the absence of any such language information, and in cases where the higher-level protocol reports multiple languages, **the language of the node is unknown, and the corresponding language tag is the empty string.**
> 
> If the resulting value is not a recognized language tag, then it must be treated as an unknown language having the given language tag, **distinct from all other languages**. 

So, it turns out that not specifying the `lang` attribute is the same as specifying it with the value of `""`, in both case the language being treated as `unknown`.

From what I've tested, browser respect the `empty string` rule (if you find one that doesn't, please let us know).
### Solution?

Having the language being treated as `unknown` isn't really much better then `lang="en"` (e.g.: VoiceOver on iOS seems to be defaulting to `English` when the language is `unknown`, no matter what the default language is).

So, I think we should make it more obvious to the user that they need to specify the `lang` attribute, by maybe:
- 1) Adding `lang=""`
  
  ``` html
  <!doctype html>
  <html class="no-js" lang="">
  ```
- 2) Adding a comment 
  
  ``` html
  <!doctype html>
  <!-- Specify the language of your content by adding the `lang` attribute to <html> -->
  <html class="no-js">
  ```
- 3) Adding `lang=""` and a comment
  
  ``` html
  <!doctype html>
  <!-- Specify the language of your content by providing a value for the `lang` attribute -->
  <html class="no-js" lang="">
  ```
- 4) Other (Which?)
## 

Thoughts?

**Comment by peterblazejewicz** [comment]
active bug topic elsewhere:
[Bug 26942 - why do these examples of <html> lack the lang attribute?](https://www.w3.org/Bugs/Public/show_bug.cgi?id=26942)
