### ISSUE TITLE
Google analytics is in the wrong spot

### ISSUE THREAD

**Issue by benburkhart1** [h5bp/html5-boilerplate#1544]
Google analytics stuff is in the wrong spot in the page load. Google's own documentation states that it should be in the &lt;head&gt; element.

Here's Google's official stance (See line item #2)
https://developers.google.com/analytics/devguides/collection/gajs/asyncMigrationExamples

It _used_ to be that with the synchronous method, placing it at the end of the body helped. Now it just prevents data from getting to google analytics if the person leaves while the page is loading.

Here's a gigantic article on the topic if you still need more convincing, but html5 boilerplate definitely has it in the wrong spot.

http://www.lunametrics.com/blog/2012/02/09/where-put-google-tracking-code/#sr=g&m=o&cp=or&ct=-tmc&st=%28opu%20qspwjefe%29&ts=1401242212

**Comment by austinpray** [comment]
What is the perf benefit as in numbers? Have you guys benchmarked it?
