### ISSUE TITLE
html5boilerplate.com is down

### ISSUE THREAD

**Issue by jasonwyatt** [h5bp/html5-boilerplate#1606]
I tried visiting http://html5boilerplate.com and it seems to be down.

**Comment by FearghalOHare** [comment]
down again :( can somebody reboot?

**Comment by drublic** [comment]
Thanks for reporting. It works for me though.
Can you please check again, maybe it was just a temporary bug. Thank you for the heads up.

**Comment by babalooi** [comment]
Site gives Error 521.

**Comment by hatzopoulos** [comment]
> Site gives Error 521
I am getting the same thing from Montreal.

`Ray ID: 1ea1af210db60fa5 • 2015-05-21 16:33:37 UTC`

**Comment by maciekpaprocki** [comment]
I cannot access it from London for like 3 weeks :(

**Comment by roblarsen** [comment]
It's not a a general outage. 
It's up according to: http://downforeveryoneorjustme.com/html5boilerplate.com
And from London specifically: http://www.webpagetest.org/result/150608_ZV_P1A/
