### ISSUE TITLE
Please, add information about files: tile.png and tile-wide.png

### ISSUE THREAD

**Issue by timfayz** [h5bp/html5-boilerplate#1639]
Hello, I've tried to find some information about these files here, but get nothing. I think, you need add some details concerning these ones.

---

Maybe I've missed something?!)

**Comment by whardson** [comment]
Hello!

 

New message, please read <http://mahanketab.com/another.php?n5cj>

 

win@affordca.com

**Comment by whardson** [comment]
Hello!

 

New message, please read <http://neox.tmpl.mk.ua/pardon.php?mn>

 

win@affordca.com
