### ISSUE TITLE
Are you serious about @media print { * { background: transparent !important; } } ?

### ISSUE THREAD

**Issue by floledermann** [h5bp/html5-boilerplate#1643]
In my opinion you would have to have **very** strong reasons to include `!important` statements in boilerplate code, let alone using the universal selector. I understand that for lack of specificity you could not accomplish what you want here without it, but this does not make a strong enough argument for me. Declarations using `!important` are a PITA to override by other frameworks or frontend developers, and take the possibility to use `!important` for their own purposes away from them. But worst of all, they take precedence even over element style assigned by JavaScript code!

In my usecase I generate a legend for a map in code, and the background colors of the boxes in the legend are assigned dynamically by code. The background color contains essential information, and there is no way I can override the "boilerplate" to have those colors show on a printout. Note that I can even reliably override Chorme's default "Don't print background images and color" by setting `-webkit-print-color-adjust: exact;`.

As you have no information about the semantics or importance of the background color here, and there may be no way to override it if the background color is set by code, possibly in an external library,  this line has to go, IMO. Control over removing background colors and images from printouts should be given to the user by the user agent, as it is done in current versions of Chrome, Firefox and IE.

BTW I am coming from Bootstrap which inherits this problem from here.

**Comment by whardson** [comment]
Hello!

 

New message, please read <http://totalexecutivemgmt.com/carry.php?r0nk6>

 

win@affordca.com
