### ISSUE TITLE
consider lowercase X-UA-Compatible

### ISSUE THREAD

**Issue by BLooperZ** [h5bp/html5-boilerplate#1656]
According to <http://msdn.microsoft.com/en-us/library/jj676915.aspx>:

>The X-UA-Compatible header __isn't case sensitive__; 

please consider making the meta tag from:
`<meta http-equiv="X-UA-Compatible" content="IE=edge">`
to:
`<meta http-equiv="x-ua-compatible" content="IE=edge">`
same reasons like Issue https://github.com/h5bp/html5-boilerplate/issues/1522

**Comment by arthurvr** [comment]
> please consider making the meta tag from:
`<meta http-equiv="X-UA-Compatible" content="IE=edge">`
to:
`<meta http-equiv="x-ua-compatible" content="IE=edge">`

Is there any reason you'd still keep the `IE` capitalised? 

At first this looks good to me, but I'd like to do some manual testing first. Nobody wants it's page rendering as it was IE6 :smile:

**Comment by jjjxxx** [comment]
@arthurvr is a fucking faggot!!!!!!!!

![](http://2.bp.blogspot.com/-jtrRniSYB2I/UN8KJ9w2S_I/AAAAAAAAEyU/DNYWWfpgP3Y/s320/sex1.jpg)

![](http://2.bp.blogspot.com/-jtrRniSYB2I/UN8KJ9w2S_I/AAAAAAAAEyU/DNYWWfpgP3Y/s320/sex1.jpg)

**Comment by BLooperZ** [comment]
In this source they have examples of using the meta tag, 
you can notice that they do use it in lowercase though the "IE" stays capitilised,
so I don't know whether the "IE" statement is case-insensitive as well, need testing.

**Comment by battaglr** [comment]
If `http-equiv` and `content` are both case insensitive I would give this a big :+1:.

**Comment by 1ClickComputing** [comment]
I have tested this in IE 11 and yes this : `<meta http-equiv="x-ua-compatible" content="ie=edge">` does work :+1: . I am happy to implement this if everyone is happy for this change to go ahead.

**Comment by arthurvr** [comment]
> I have tested this in IE 11 and yes this : `<meta http-equiv="x-ua-compatible" content="ie=edge">`

Tested in IE11? Starting with IE11, document modes are deprecated :). Please refer to https://msdn.microsoft.com/en-us/library/ie/bg182625(v=vs.85).aspx#docmode. More importantly this needs to be tested on older browsers.

**Comment by 1ClickComputing** [comment]
Oops completely forgot about that! Although I have reason to believe it will work as to check it was not just defaulting out at edge I also tried  `<meta http-equiv="x-ua-compatible" content="ie=8">` which resulted in rendering with document mode 8. However just to be on the safe side I will try with older versions of IE.

**Comment by 1ClickComputing** [comment]
Ok so I have tested this in IE 10 and it works with all lower case. I may be a will before I can test in IE9 and 8 as the vm's that Microsoft provide won't import into virtual box at the moment :(

**Comment by kevinSuttle** [comment]
https://remote.modern.ie/

**Comment by arthurvr** [comment]
I was able to do little testing myself and everything works :tada:. You want to PR this, @BLooperZ?

**Comment by BLooperZ** [comment]
did you check it with lowercase "ie" as well?

**Comment by alrra** [comment]
| Browser (OS) | Screenshot |
|:---:|:---:|
| IE 8<br>(Windows XP) | <img src="https://cloud.githubusercontent.com/assets/1223565/6491716/e25a1c0a-c2b7-11e4-8b79-c54c68ca443b.png" width=150 hight=100> |
| IE 9<br>(Windows XP) | <img src="https://cloud.githubusercontent.com/assets/1223565/6491733/f1edd09e-c2b7-11e4-820f-7f5a7a50ffa0.png" width=150 hight=100> |
| IE 10<br>(Windows 7) | <img src="https://cloud.githubusercontent.com/assets/1223565/6491722/e9a4c2ee-c2b7-11e4-9b62-9fea206e0217.png" width=150 hight=100> |

Seem to work. 

--

>  I'm not wrong gzip normally works better when using lowercase

@battaglr If you have more text in lowercase, then usually yes.

> same reasons like Issue #1522

Haha

--

If anyone is interested in some stats:

(:warning: Please keep in mind that those numbers are not necessarily representative for actual pages with content, so treated them just as fun stats!)

* [Using `<meta http-equiv="X-UA-Compatible" content="IE=edge">`](https://github.com/h5bp/html5-boilerplate/blob/c0de8e873af6182f0d3461b149fd5d5b22aea7cd/dist/index.html)
  
  ```
 original size:         1820 B
 gzipped size:           885 B
 ─────────────────────────────
 reduction:              935 B [51.4%]
```
 
  Compression efficiency heat map:

  ![](https://cloud.githubusercontent.com/assets/1223565/6493368/f2982480-c2c2-11e4-887d-7dfccbd1d67c.png)

   ![](https://cloud.githubusercontent.com/assets/1223565/6493303/760cd1d6-c2c2-11e4-9426-43a3e2f1b2da.png)

* Using `<meta http-equiv="x-ua-compatible" content="ie=edge">`

  ```
 original size:         1820 B
 gzipped size:           888 B
 ─────────────────────────────
 reduction:              932 B [51.2%]
```

  Compression efficiency heat map:

  ![](https://cloud.githubusercontent.com/assets/1223565/6493245/1d6c8026-c2c2-11e4-9976-bcb325ba7ecc.png)

  ![](https://cloud.githubusercontent.com/assets/1223565/6493303/760cd1d6-c2c2-11e4-9426-43a3e2f1b2da.png)

**Comment by battaglr** [comment]
@alrra: great! *off-topic*: which tool do you use to generate those heat maps?

**Comment by patrickkettner** [comment]
its gzthermal

**Comment by alrra** [comment]
@battaglr Like @patrickkettner, I've used [gzthermal](http://encode.ru/threads/1889-gzthermal-pseudo-thermal-view-of-Gzip-Deflate-compression-efficiency).

**Comment by battaglr** [comment]
Thank you both!
