### ISSUE TITLE
Include prefixfree to dist

### ISSUE THREAD

**Issue by artemist** [h5bp/html5-boilerplate#1661]
Would it be worthwhile to include http://leaverou.github.io/prefixfree/ to automatically remove vendor prefixes? There are a lot of builds that allow for this option already, but it might be nice to have it in the dist file so that people could use or not use it to their discretion.

**Comment by battaglr** [comment]
> -prefix-free lets you use only unprefixed CSS properties everywhere.

It doesn't remove the vendor prefixes, it just adds them on runtime. Anyhow, I don't think this should be included. Using JavaScript to add vendor prefixes is not a desirable practice, at least on this kind of projects.

In any case I would suggest [Autoprefixer](https://github.com/postcss/autoprefixer). But H5BP is not that prescriptive about tooling.

Cheers.

**Comment by roblarsen** [comment]
This is similar to the Fastclick suggestion, I think (#1574 ) Useful but not something that would normally be included at this level.

**Comment by artemist** [comment]
ok sounds good.
