### ISSUE TITLE
.hidden class doesn't need visibility:hidden

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5-boilerplate#1663]
https://twitter.com/patrick_h_lauke/status/563021544344260609

**Comment by jonathantneal** [comment]
To summarize, `display: block` and `visibility hidden` were there to prevent hidden content from being read in Windows-Eyes and JAWS ([reference](http://juicystudio.com/article/screen-readers-display-none.php))

The bug as seen in Window-Eyes 5.5 has since been [resolved](https://twitter.com/patrick_h_lauke/status/563268381470896128) in Windows-Eyes 9, and possibly earlier versions.

I am waiting to see if the issue with JAWS 7.1 has also been resolved.

**Comment by alrra** [comment]
## Test page

 ```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Test</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>

        .hidden {
            display: none !important;
        }

        .bg {
            background:url('https://avatars1.githubusercontent.com/u/1136800?v=3&s=200');
            color: #fff;
        }

    </style>
</head>
<body>

    <a href="https://html5boilerplate.com/">
         Test 1 did
         <span class="hidden">not</span>
         pass
     </a>

     <div class="bg">
         Test 2 did
         <span class="hidden">not</span>
         pass
     </div>

</body>
</html>
```

The page takes into consideration the test cases described in [this article](http://juicystudio.com/article/screen-readers-display-none.php). If there are any problems the screen readers should say: "Test x did NOT pass".

## Tests

I've tested using Internet Explorer 11 on Windows 7, and the results are as follow: 

* :x: `JAWS v10`

  <a href="https://dl.dropboxusercontent.com/u/479990/tests/html5-boilerplate/1663/jaws_v10.mp4"><img src="https://cloud.githubusercontent.com/assets/1223565/6527683/529d8006-c425-11e4-960c-d2a3244692fc.png" alt="JAWS v10"></a>

*  :ballot_box_with_check: `JAWS v12` 

  <a href="https://dl.dropboxusercontent.com/u/479990/tests/html5-boilerplate/1663/jaws_v12.mp4"><img src="https://cloud.githubusercontent.com/assets/1223565/6527714/b0060cc2-c425-11e4-8fa9-19f69044aa58.png" alt="JAWS v12"></a>

*  :ballot_box_with_check: `JAWS v16` (latest version)

  <a href="https://dl.dropboxusercontent.com/u/479990/tests/html5-boilerplate/1663/jaws_v16.mp4"><img src="https://cloud.githubusercontent.com/assets/1223565/6527729/c9c178a4-c425-11e4-872b-14db0a9ec448.png" alt="JAWS v16"></a>


*  :ballot_box_with_check: `Window-Eyes v9` (latest version)

  <a href="https://dl.dropboxusercontent.com/u/479990/tests/html5-boilerplate/1663/window-eyes_9.mp4"><img src="https://cloud.githubusercontent.com/assets/1223565/6527577/6a4b6bf6-c424-11e4-9364-061ee3c52474.png" alt="Windows-Eyes v9"></a>

--

It seems the problems stated in [this article](http://juicystudio.com/article/screen-readers-display-none.php) are resolved in both JAWS (sometime before or with `v12`) and Windows-Eyes (I wanted to test in a version prior to version 9, but I couldn't make that version work).
