### ISSUE TITLE
Move the content of the `main.css` and `plugins.js` files into their own repositories 

### ISSUE THREAD

**Issue by alrra** [h5bp/html5-boilerplate#1671]
I think it would be a good idea to move the content of the [`main.css`](https://github.com/h5bp/html5-boilerplate/blob/9318c6321a8b85b41f83ae67a6b23c5cd59921a4/src/css/main.css) and [`plugins.js`](https://github.com/h5bp/html5-boilerplate/blob/9318c6321a8b85b41f83ae67a6b23c5cd59921a4/src/js/plugins.js) files into their own repositories so that other projects can also easily consume them via a package managers such as [`npm`](https://www.npmjs.com/) and [`bower`](http://bower.io/).

I'm think of:
- [h5bp-base-css](https://github.com/h5bp/html5-boilerplate/blob/697fa65431bcafae222f13f574e27b1f21f81286/src/css/main.css#L1-L203)
- [h5bp-print](https://github.com/h5bp/html5-boilerplate/blob/697fa65431bcafae222f13f574e27b1f21f81286/src/css/main.css#L204-L280)
- [h5bp-console](https://github.com/h5bp/html5-boilerplate/blob/697fa65431bcafae222f13f574e27b1f21f81286/src/js/plugins.js#L1-L22)

(feel free to suggest better names!)
## 

Notes: 
- This change will also allow us to provide variants of the files (e.g.: SASS, LESS, CoffeeScript, etc.).
- There are already some ["unofficial"](https://www.npmjs.com/package/h5bp-print-styles) packages, but I think we should provide are own "official" ones that also [maintain the commit history of the files](https://github.com/h5bp/server-configs/pull/104).

**Comment by sandrodz** [comment]
Yes, I'm manually removing normalize and modernizr and including them with bower. Would be cool if you would just include bower.json file or npm equivalent under customizer.

**Comment by d10** [comment]
I think this might be useful only if a lot of people just use certain sections of H5BP’s CSS, which would make it easier by allowing easy installation via package managers etc. However if the number is people who do so is quite small, it might mean a lot more work maintaining separate repositories. Currently, the most important thing to do would be to spread the word obtain feedback.

**Comment by d10** [comment]
I think this might be useful only if a lot of people just use certain sections of H5BP’s CSS, which would make it easier by allowing easy installation via package managers etc. However if the number is people who do so is quite small, it might mean a lot more work maintaining separate repositories. Currently, the most important thing to do would be to spread the word obtain feedback.

**Comment by arthurvr** [comment]
In general I'm a +1 on this, but I would opt to first do it with `main.css` and look into the rest later. The `main.css` file is something many third-parties depend on (thinking about yeoman generators, other boilerplates, ...) but this might, in the future, even be useful for mobile boilerplate. For the other files, I don't really think we should move them around (yet).

We could easily have all these files under `dist/` using the same technique we use for the `.htaccess` file. 

If we all like this, feel free to assign to me. I have the time to do it.

> This change will also allow us to provide variants of the files (e.g.: SASS, LESS, CoffeeScript, etc.).

For sure, that would be nice.

/cc @h5bp/html5-boilerplate

**Comment by QWp6t** [comment]
:+1:

**Comment by koistya** [comment]
One of the pros to keep those files in the same project, is that this way its easier to use h5bp repo as a reference, which you can open and fine all the stuff you're looking for within the same repo.

**Comment by arthurvr** [comment]
@koistya That will still be possible as (I think) we will still commit the `dist/` directory.

**Comment by roblarsen** [comment]
:+1: 
I think this is a great idea.

**Comment by alrra** [comment]
> One of the pros to keep those files in the same project, is that this way its easier to use h5bp repo as a reference, which you can open at any time and find all the stuff you're looking for within the same repo.

> Maybe it's better to do this breaking into modules stuff inside the yeoman h5bp generator instead?

@koistya As @arthurvr said, the files will still be present in the `dist/` directory, so they won't go away from this project. It will basically be [the same as with the `.htaccess` file](https://github.com/h5bp/html5-boilerplate/blob/3be7fe5c01638c3390aa064fe5783bfa5613cb02/package.json#L3).

> Currently, the most important thing to do would be to spread the word obtain feedback.

@d10 As far as other projects go, quite a few would benefit from this, or even specifically asked from it (e.g.: [1](https://github.com/twbs/bootstrap/blob/master/less/print.less), [2](https://github.com/google/web-starter-kit/issues/609)). 

--

Cc: @XhmikosR , @cvrebert

**Comment by XhmikosR** [comment]
It's a good idea regarding modularity so :+1: 

In our case, we have some custom code so it's simpler if we just include the file. Not sure if those changes could/should be included upstream here; maybe @cvrebert can shed some light on this.

**Comment by paulirish** [comment]
:+1: SGTM. 

Maybe we need a transition to not freak people out.. Like we could use a `this-has-moved.md` file in their place in /src ?   (And we'd nuke in the build).

**Comment by arthurvr** [comment]
@paulirish IMHO we should have a note in `contributing.md` about the current structure of this repo anyways. [People still seem to confuse our structure with build scripts.](https://github.com/h5bp/html5-boilerplate/issues/1624).

**Comment by battaglr** [comment]
:+1:

**Comment by alrra** [comment]
> There are already some "unofficial" packages, 

https://docs.npmjs.com/getting-started/scoped-packages

**Comment by ramasilveyra** [comment]
This is great and publish `main.css` on bower independently

**Comment by roblarsen** [comment]
Two years later... Post-6.0 this will be my priority. I think this is great.

**Comment by bueltge** [comment]
#2046 has the goal to separately the print stylesheet and maybe this is a small step to close this issue, currently also with a technical change, pull request #2047

**Comment by roblarsen** [comment]
I'm officially starting work on this... the project JavaScript requires more discussion, so I'm going to table that for now (although I want to do it.) main.css will get moved to a new repo for 6.2

**Comment by roblarsen** [comment]
#2066 and [h5bp/main.css/pull/5](https://github.com/h5bp/main.css/pull/5)

I'm close on the 1.0.0 of the main.css which means I can then finish #2066 and it'll be magical.

**Comment by roblarsen** [comment]
I'm going to open a 7+ issue in the repo to discuss what the boilerplate JavaScript should look like in this project (different, yes, but how?)  and am going to close this issue, since [main\.css 1.0.0](https://github.com/h5bp/main.css/releases) was just released and is live on [npm](https://www.npmjs.com/package/main.css).
