### ISSUE TITLE
Add metadata documentation for social networks and search engines.

### ISSUE THREAD

**Issue by QWp6t** [h5bp/html5-boilerplate#1674]
I don't think this should be included in index.html, but I think we could add brief documentation and link out to third-party resources for the following...

**Google+ / Schema.org**
```html
<link rel="author" href="">
<link rel="publisher" href="">
<meta itemprop="name" content="">
<meta itemprop="description" content="">
<meta itemprop="image" content="">
```

**Search Engines**
```html
<meta name="author" content="">
<meta name="description" content="">
<link rel="canonical" href="">
```

**Twitter**
```html
<meta name="twitter:card" content="">
<meta name="twitter:site" content="">
<meta name="twitter:creator" content="">
<meta name="twitter:title" content="">
<meta name="twitter:description" content="">
<meta name="twitter:image:src" content="">
```

**Facebook / Open Graph**
```html
<meta property="fb:admins" content="">
<meta property="fb:app_id" content="">
<meta property="og:url" content="">
<meta property="og:type" content="">
<meta property="og:title" content="">
<meta property="og:image" content="">
<meta property="og:description" content="">
<meta property="og:site_name" content="">
<meta property="article:author" content="">
<meta property="article:publisher" content="">
```

Credit where it's due: I got this idea after seeing how neatly organized @scotch-io's metadata was.

**Comment by alrra** [comment]
> add brief documentation and link out to third-party resources 

@QWp6t Updates to the [existing documentation](https://github.com/h5bp/html5-boilerplate/blob/78c84ce70185ff0fc513957eb5f4270672b43a7e/src/doc/extend.md#social-networks) are always welcomed! Care to open a pull request?

**Comment by peterblazejewicz** [comment]
:+1: 
I'd also add relevant tools links (validators) in the same order as above examples:
- https://developers.google.com/structured-data/testing-tool/
- https://cards-dev.twitter.com/validator
- https://developers.facebook.com/tools/debug/

**Comment by alrra** [comment]
ping @QWp6t

**Comment by JamesIves** [comment]
If this is still needed I'd be happy to contribute. Let me know.

**Comment by arthurvr** [comment]
@JamesIves Glad to hear that! I don't think anybody's working on this so feel free :)

**Comment by clarkdemvher** [comment]
Sent from Samsung tablet.


-------- Original message --------

**Comment by clarkdemvher** [comment]
Sent from Samsung tablet.


-------- Original message --------

**Comment by T1st3** [comment]
Still no one on this? I'm ready to go for a PR
