### ISSUE TITLE
Boilerplate Google Analytics code different than script from Google analytics

### ISSUE THREAD

**Issue by waterworks** [h5bp/html5-boilerplate#1676]
I signed up for Google Analytics today and they provided this tracking code

` (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-XXXXXXXX-X', 'auto');
  ga('send', 'pageview');`

I also downloaded boilerplate5 template files today and noticed the tracking code is different

`(function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
  function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
  e=o.createElement(i);r=o.getElementsByTagName(i)[0];
  e.src='//www.google-analytics.com/analytics.js';
  r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
  ga('create','UA-XXXXXXXX-X','auto');ga('send','pageview');`

GA's function () spells out ISOGRAM, while BP5's function spells out BOILER, along with other noticeable differences. Is it best to use the BP5 or GA code?

Note: This is not a question regarding the placement of Google Analytics within the web document which has been discussed at length on other threads.

**Comment by alrra** [comment]
> GA's function () spells out ISOGRAM, while BP5's function spells out BOILER, along with other noticeable differences. 

@waterworks We include a [optimized version of the Google Universal Analytics](https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/html.md#google-universal-analytics-tracking-code).

**Comment by waterworks** [comment]
Thank you sir! I missed the word 'optimized' in the documentation. Much appreciated. :)

Great job everyone who worked on BP5. The whole project is so incredibly helpful!
