### ISSUE TITLE
Why not make browsehappy IE9-?

### ISSUE THREAD

**Issue by corysimmons** [h5bp/html5-boilerplate#1688]
IE9 is still a really old browser.

**Comment by patrickkettner** [comment]
what feature is missing in IE 9 that would warrant it

**Comment by corysimmons** [comment]
A lot? http://html5test.com/results/desktop.html

**Comment by patrickkettner** [comment]
thats a list of features missing that ie 9 doesn't have. Im asking what feature does IE 9 lack that makes it noticeably harder to make the average website? IE 8 has a buttload. IE 9 doesn't (in my opinion).

Obviously its not latest chrome or firefox, but it does has a vast majority of features that most modern (not cutting edge) websites need. Browsehappy is a pretty in-your-face sort of thing for a default on a browser that works decently for a large amount of websites.

**Comment by hatzopoulos** [comment]
With the recent [news](http://www.theregister.co.uk/2015/01/21/microsoft_giving_windows_10_away_free_for_windows_7_81_and_phone_users/) about Microsoft giving away Windows 10, maybe we can get the ball rolling and help people upgrade their entire OS while we're at it.

:)

**Comment by corysimmons** [comment]
There are a myriad of things that are worse in IE9 than IE11... I'm not sure why I have to list them all..

Nevermind. Keep the repo however you want.

**Comment by patrickkettner** [comment]
Im not on the team duder - just having a converstaion

**Comment by alrra** [comment]
> Why not make browsehappy IE9-?

@corysimmons Because this projects still [supports IE 8+](https://github.com/h5bp/html5-boilerplate#browser-support). However, in your own copy/fork, you are free and even encouraged to change things to better suit your particular needs.

**Comment by corysimmons** [comment]
Already did https://github.com/corysimmons/boy

**Comment by corysimmons** [comment]
@patrickkettner List of common features IE still doesn't have https://wpdev.uservoice.com/forums/257854-internet-explorer-platform

**Comment by patrickkettner** [comment]
Hey dude,
im sorry if I was confusing or unclear - I didn't mean what does chrome or firefox has that IE 9 doesn't. That is easy to find.

What I am saying is what feature would the average website _need_ that IE 9 does not have. _That_ is why the browse happy thing exists. If for your use case you think it should be there for IE 9, then by all means, modify the boilerplate to be that way. But the boilerplate is a group of best practices for most websites. In order for this project to say that any client visiting the average website should get this big ol popup, we would want to nail down specific features that are greatly detrimental to the web authoring experience.

if you look down that list you'll see a ton of amazing, awesome, cutting edge features

- shadow dom
- custom elements
- template plugins
- asm
and the list goes on...

I love and use most of those on a regular basis, but I don't think the average website does.


plus, @alrra is the man in charge, and as he said "this projects still supports IE 8+."

**Comment by corysimmons** [comment]
Not a problem. Thanks for your guys work on H5BP. Makes an excellent fork.
