### ISSUE TITLE
X-UA compatible and IE conditional headers

### ISSUE THREAD

**Issue by callmemagnus** [h5bp/html5-boilerplate#1690]
Hi,

I got recently in trouble because of 

    <!DOCTYPE html>
    
    
    
     <html class="no-js"> 

and

    <meta http-equiv="X-UA-Compatible" content="IE=edge">

In a environment, where IE9 was forced to run as IE7 (for "internal" sites).

The issue is that the code in the boiler plate does not work as expected.

The issue is that before we even tell (a forced compatibility) IE to work in "edge" mode, we are asking it to tell us which version it is. Therefore the X-UA-Compatible has no effect: the decision is already taken.

In order to have working, I had to do the IE conditional stuff later in the page or to move the X-UA-Compatible in the server headers. But this is out of scope of the boilerplate. 

This is not really an issue but more a remark to the existing code.

Tell me if I'm completely wrong.

**Comment by patrickkettner** [comment]
Nope! You are not wrong at all, we talked about it in #378

**Comment by patrickkettner** [comment]
Note that boilerplate doesn't actually support ie7. Its ie8+

**Comment by battaglr** [comment]
Never thought about it. Maybe this could be mentioned in the docs?

**Comment by callmemagnus** [comment]
In any case, the current implementation will fail in "compatibility forced" environments.

This happens when microsoft domain admins follow blindly the microsoft tutorial to setup their corporate ADs. They use their external domain as internal microsoft domain. Then they install a crappy web interface that needs/requires IE7 or 8 to run, so they have to block all viewing of sites on the "domain" (aka internal websites") to IE7 or 8 (hence the forced compatibility mode). 

So for the public website seen from inside...

By not doing like in my first comment, I drastically reduce the amount of bugs reported on IE7 (because that is the enforced compatibility level).

yes, you can light a candle to save my soul...

**Comment by battaglr** [comment]
Placing the IE conditionals in the `<body>` should fix that use-case even when only using the `<meta>`, right?

Is there a strong reason why the conditionals are placed in the `<html>` and not in the `<body>`?

**Comment by mzgol** [comment]
The latest HTML5 Boilterplate doesn't use this kind of conditional comments.

**Comment by alrra** [comment]
> In order to have working, I had to do the IE conditional stuff later in the page or to **move the X-UA-Compatible in the server headers**

@callmemagnus From https://github.com/h5bp/html5-boilerplate/blob/bf141af5078b5e82b12dfc09b9406e077096fa27/dist/doc/html.md#x-ua-compatible

> If possible, we recommend that you remove the meta tag and send only the HTTP response header as the meta tag will not always work

--

>  the conditionals are placed in the <html> and not in the <body>?

@battaglr See: https://github.com/h5bp/html5-boilerplate/issues/44.

**Comment by battaglr** [comment]
@alrra: that makes sense, thanks for the reference!

**Comment by callmemagnus** [comment]
@alrra yeah, but may not be always possible.
