### ISSUE TITLE
humans.txt not licensed for commercial websites and H5BP users should be notified

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1704]
Because humanstxt.org licenses its content, including the file meant for us to use, for noncommercial use only ("humans.txt is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License", linking ultimately to http://creativecommons.org/licenses/by-nc-sa/3.0/legalcode (more or less summarized at http://creativecommons.org/licenses/by-nc-sa/3.0/)) (all as accessed in the last few minutes), you should reiterate that limitation where you advise in /doc/usage.md that users should "[e]dit this file to include the team that worked on your site/app, and the technology powering it." Thinking their choice of license might have been inadvertent, I emailed humanstxt.org last May 2. No one replied. The page still refers to the noncommercial-only license. For example, if I arrange for Google to send ads to a site of mine and pay me for them, that site probably cannot have a standard humans.txt file without permission for which I may have to pay. As a result, although humans.txt is a nice concept I'd be willing to use, I can't legally use it in the standard format. If the H5BP organization is itself noncommercial, it can use and distribute the standard humans.txt, but people using the H5BP download have to reformat the file or honor the limit against commercial use and should be told of it so the H5BP organization is not facilitating other people's copyright infringements (such a facilitation would be a legal offense separate from infringement itself).

I think that naming a file humans.txt but not copying the standard content or format, making up something else altogether (like in <http://www.google.com/humans.txt>, as accessed in the last few minutes) is not a copyright violation because publication names and short phrases cannot be copyrighted, so that the license and its limitations are legally irrelevant for those. On the other hand, I don't know if a filename is a publication name.

Humanstxt.org had a noncommercial limitation back on July 3, 2011, but not earlier on January 17, 2011, based on a search in archive.org, as of last Thursday. I didn't check most other archived dates. I gather from comments in this GitHub area and a Whois lookup that humanstxt.org was founded in 2011. So it appears that it began without a limitation but that the limitation was added in the next few months. I did not search to find out why. Perhaps the founder/s associated with H5BP intended that there be no limit on humans.txt, but someone added it, for whatever reason. No one may have enforced a claim against any user to date, but they can.

**Comment by alrra** [comment]
@cabans, @abelsutilo, @oneeyedman, @juanjoBer, @MaJoseBravo :arrow_up:

**Comment by farrukhsubhani** [comment]
@talibh

**Comment by iron16** [comment]
The Creative Commons statement in the site footer is most likely about the humanstxt.org site and not humans.txt itself.

**Comment by QWp6t** [comment]
This is a silly non-issue.

Humans.txt is likely not even copyrightable since it's literally just a set of facts, and facts aren't copyrightable. But even if it were copyrightable, then as long as you're not literally copying their exact human.txt file, then your work is transformative enough that it would not be infringing.

**Comment by Nick-Levinson** [comment]
No, the site's home page (as of a few minutes ago) says the license applies to "humans.txt", not "humanstxt.org". Maybe they meant to copyright and license the site alone, but that's not what they did, and they didn't respond about a year ago to my email, so we should assume they did what they intended to do.

Arrangement and enhancement are copyrightable. A telephone book is copyrightable and so is a state- or city-government-created transit map. Underlying information is not copyrightable but its expression generally is. A major relevant exception is that if there is no other way to express only the underlying information then the form of expression may not be copyrightable, but that doesn't apply here. What's visible at http://humanstxt.org/humans.txt (as of a few minutes ago) is one form of expression but one not so basic as to be beyond copyright; it's covered.
