### ISSUE TITLE
html5boilerplate.com is down

### ISSUE THREAD

**Issue by FearghalOHare** [h5bp/html5-boilerplate#1705]
?
:(

**Comment by arthurvr** [comment]
Hmm... not for me. http://downforeveryoneorjustme.com/html5boilerplate.com/. Where are you trying to access it from? Maybe there was just something temporary. @paulirish?

**Comment by FearghalOHare** [comment]
nope def down from ireland. tried my phone, and 2 desktops from 2 diff nw

**Comment by FearghalOHare** [comment]
Can yon send link to the boilerplate zip please?

**Comment by marcobiedermann** [comment]
@FearghalOHare You can download the zip from master branch
https://github.com/h5bp/html5-boilerplate/archive/master.zip

**Comment by gmcnaughton** [comment]
It's down for me too.  I'm trying to access it from the UK - I get a CloudFlare error page saying "Error 521 Web server is down".  Here's a screenshot:

![screenshot](http://i.imgur.com/numZwc5.jpg)

**Comment by marcobiedermann** [comment]
Yup, down from Germany as well

**Comment by arthurvr** [comment]
Thanks for letting us know! I pinged Paul (he owns the server).

**Comment by arthurvr** [comment]
All fixed. Thanks @paulirish! Please do let us know when you experience more troubles.

**Comment by FearghalOHare** [comment]
Thx a mil
On 21 May 2015 6:10 pm, Arthur Verschaeve <notifications@github.com> wrote:Closed #1705.

**Comment by joshyop** [comment]
@arthurvr sere are some dicks for you fag

<img src="http://garibaldi-gay.com/wp-content/uploads/2010/01/gay_sex_002_st_500.jpg">
