### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by newton43** [h5bp/html5-boilerplate#1706]
I see that the last commit was done a long time ago in terms of open source time and there isn't much activity here on github. :(

**Comment by quantumpacket** [comment]
Last commit was 25 days ago, that is active in my opinion. Also, how much do you expect HTML5 to change day to day?

**Comment by roblarsen** [comment]
It's not the kind of codebase that has a lot of churn. That's been the case for many years. 

That said, there have been three releases this year, including a new [major release](https://github.com/h5bp/html5-boilerplate/releases/tag/5.0) and a minor release (with two interesting changes) 25 days ago.

**Comment by webhat** [comment]
It takes a little longer that 25 for a project to be dead, I suggest you have a look at a projects [Pulse on GitHub](https://github.com/h5bp/html5-boilerplate/pulse) so you can see all the activity.

**Comment by roblarsen** [comment]
@paulirish sighting!
