### ISSUE TITLE
Typo in .htaccess file

### ISSUE THREAD

**Issue by Alhadis** [h5bp/html5-boilerplate#1707]
On [line #206](https://github.com/h5bp/html5-boilerplate/blob/master/dist/.htaccess#L206), the word `"them"` is misspelt `"then"`.
```apache
  205    # Serving `.ico` image files with a different media type
- 206    # prevents Internet Explorer from displaying then as images:
+ 206    # prevents Internet Explorer from displaying them as images:
  207    # https://github.com/h5bp/html5-boilerplate/commit/37b5fec090
```
That's all. =)

**Comment by drublic** [comment]
Thank you for reporting. This is a problem with [h5bp/server-configs-apache](https://github.com/h5bp/server-configs-apache). We'll take care of it.
