### ISSUE TITLE
unused mobile directories/subdomains and common mistyping

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1710]
I gather that, because some websites deal with mobile design by creating separate directories for content formatted to fit (while others use responsive CSS), some users or user agents might attempt to visit such directories. For responsive design, I've seen advice to redirect visits to certain subdomains and directories to the home page. For directories, since redirection is handled in the .htaccess file (my host runs Apache), I've added something like the following to mine:

[comment line] Redirect from /i & /mobile to the home page.
RedirectPermanent /i http://example.com
RedirectPermanent /mobile http://example.com

Perhaps this should be added to H5BP's model .htaccess file, as an option for either commenting out or decommenting.

The third-level domains m and wap (as in m.example.com and wap.example.com) could be handled for the same reason by setting them up as aliases and perhaps that should be suggested somewhere in your documentation.

I forgot where I saw the advice, so I don't know whom to credit.

Firefox responds to failed attempts to reach Web addresses by suggesting proofreading one's typing, giving "ww.example.com" as the illustration. So I added that as an alias. If Firefox is right to to give that error primacy, maybe it's common, and it should be added to your documentation as a suggestion.

**Comment by Nick-Levinson** [comment]
Also, as the original poster, I would add /mobi to the list of redirects from /mobile and /i to the home page, because, if the TLD *.mobi grows in use, people may search for that as a directory, even though erroneous, so we may as well catch it in <.htaccess>.

**Comment by arthurvr** [comment]
> Perhaps this should be added to H5BP's model .htaccess file, as an option for either commenting out or decommenting.

From the contributing.md: 

> Please do not open issues or pull requests regarding the code in .htaccess

Can you reopen this at the [`server-configs-apache`](https://github.com/h5bp/server-configs-apache) repo? Thanks.
