### ISSUE TITLE
Remove <link rel="stylesheet" href="css/normalize.css"> from index.html

### ISSUE THREAD

**Issue by JGallardo** [h5bp/html5-boilerplate#1711]
Line 13 has
`<link rel="stylesheet" href="css/normalize.css">`

But the CSS files does not have `normalize.css`. I always recall it being in there but since for whatever reason it is not, then it should be removed from the default `index.html` file

**Comment by quantumpacket** [comment]
It's right here https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/normalize.css

**Comment by arthurvr** [comment]
As @quantumpacket pointed out it's still there. Maybe you was looking at the `src` directory? Only the source files live there, not vendor files like this.
