### ISSUE TITLE
Remove space in viewport meta tag

### ISSUE THREAD

**Issue by WebNinjrDesign** [h5bp/html5-boilerplate#1716]
Can we remove the space in the meta tag

    <meta name="viewport" content="width=device-width, initial-scale=1">

and make it this...

    <meta name="viewport" content="width=device-width,initial-scale=1">

in the index.html file for better compression and file size?

Here it says its a comma separated list, so i don't really see any issue with it.
https://developer.mozilla.org/en/docs/Mozilla/Mobile/Viewport_meta_tag

**Comment by drublic** [comment]
Thanks for the though.
Does this new solution really compress better with via gzip? Can you please add some numbers here?
I would rather opt for better readability here. Personally I think removing whitespace is something a tool can handled if really needed.

**Comment by mathiasbynens** [comment]
> Does this new solution really compress better with via gzip?

There is no universal answer to this; it depends on the rest of the content of the HTML file. I’d assume that for most text documents a comma followed by a space is more common than a comma followed by `i`, and therefore gzip might give slightly better results with the space.

**Comment by drublic** [comment]
Makes sense. Thanks for clarifying, @mathiasbynens.

**Comment by WebNinjrDesign** [comment]
Sorry, really should have done my research first on GZIP. Thanks for the responses.

**Comment by drublic** [comment]
No worries. Thank you for bringing it up :)
