### ISSUE TITLE
Flexbox support

### ISSUE THREAD

**Issue by dandv** [h5bp/html5-boilerplate#1718]
Pardon me if flexbox support is not within the scope of H5BP (I did search through the 1000+ issues, and there's no occurrence of "flexbox").

After dropping IE support (#1524), it would be nice to migrate towards flexbox. Global support is at [93%](http://caniuse.com/#feat=flexbox) now.

This would finally get rid of the clearfix hack and make sticky footer (#117) very easy.

Even while offering IE8 support, flexbox can still be used - see [Real world flexbox](http://www.planningforaliens.com/blog/2014/03/11/real-world-flexbox/).

**Comment by danellebailey** [comment]
What is required to make this happen? I'm new to the group but want to help out with this project. Thanks!

**Comment by WebNinjrDesign** [comment]
Once H5BP drops support for IE8 (as you mentioned) it will still support IE 9, which does not support flexbox, and thus our old clearfix friend is still needed, so i dare say it will still be a little while before they remove the clearfix helper in H5BP.

**Comment by danellebailey** [comment]
@WebNinjrDesign How do I read more on what the group officially supports and is working toward in regard to browser support, etc? Thank you!

**Comment by drublic** [comment]
Thanks for your report. HTML5 Boilerplate is not a framework. We don't provide a lot of helper classes and don't add anything concerning layout. I don't think integrating something like a flexbox boilerplate is out of scope for us.

**Comment by alrra** [comment]
Closing for the [reasons](https://github.com/h5bp/html5-boilerplate/issues/1718#issuecomment-138913300) specified by @drublic.
