### ISSUE TITLE
Two warnings, please help!

### ISSUE THREAD

**Issue by Denisov21** [h5bp/html5-boilerplate#1719]
I used the html 5.5.2 template but the W3C Validator reports two warnings . How can I fix? Can you help me please?

The Content-Type was “text/html”. Using the HTML parser.	
Using the schema for HTML with SVG 1.1, MathML 3.0, RDFa 1.1, and ITS 2.0 support.

**Comment by Denisov21** [comment]
Fix, excuse me!

**Comment by Rubel-hossain** [comment]
Those are not warnings. They are informational notes.

Your document is fine.

**Comment by Denisov21** [comment]
Thank you!
