### ISSUE TITLE
Normalizing <i> tags

### ISSUE THREAD

**Issue by SergeRNR** [h5bp/html5-boilerplate#1721]
Hi,
I've found that "i" tag style is missing in the normalize.css file. Some common css-reset rules sets font as "inherit" and it would be great to restore "font-style: italic" property.

**Comment by clarkdemvher** [comment]
Sent from Samsung tablet.


-------- Original message --------

**Comment by danellebailey** [comment]
Hello Serge, 

I think this may help. http://www.impressivewebs.com/bold-italic-html5/ 

<i> is not specific to italics anymore.

**Comment by WebNinjrDesign** [comment]
normalise.css is not in place to fix what resets do, it's a replacement for resets. It's best used without resets (in my personal opinion).

It has been develop to standardise styling across browsers, and as all browsers (that I'm aware of) style 'i' tags with italics, its not required in normalise.css.

However if your preference is to use a css reset AND normalise.css then you will probably want to keep this up your sleeve as snippet on your own sites.

Also, normalise.css is maintained separately to H5BP, if you feel it is still an issue, you should post it as an issue here instead: https://github.com/necolas/normalize.css/

**Comment by danellebailey** [comment]
This is helpful. Thank you, @WebNinjrDesign!

**Comment by drublic** [comment]
Thank you for the discussion. Is there any browser which does not show `<i>` as italic by default? Otherwise I don't think there is a need for normalization.

**Comment by danellebailey** [comment]
Good point. It is still rendered presentationally as italic, but has additional semantic meaning. Thanks!

**Comment by drublic** [comment]
I am closing this issue now. Thanks for raising this issue.
