### ISSUE TITLE
gulp - serve - src dist - improved documentation / adding gulp tasks?

### ISSUE THREAD

**Issue by stefek99** [h5bp/html5-boilerplate#1726]
I haven't been using H5BP for some time and I've noticed some changes. Specifically - https://github.com/h5bp/html5-boilerplate/commit/9318c6321a8b85b41f83ae67a6b23c5cd59921a4 - introducing new project architecture that uses src / dist / gulp build system.

As I'm editing the webpage I should edit **src** directory, right?

But it kind of sucks, as the jQuery is loaded from the following URL: ```https://ajax.googleapis.com/ajax/libs/jquery/{{JQUERY_VERSION}}/jquery.min.js```

As the jQuery is not loaded, other scripts do not work 

I tried searching for a task to serve (and livereload) the website as I'm editing it - https://github.com/h5bp/html5-boilerplate/blob/master/gulpfile.js - but there is only build.

Building site everytime I made a change is a slow process.

---

Maybe I'm missing something so please explain - how do you serve your website in development mode when jQuery is loaded via {{version}} link?

**Comment by TheDutchCoder** [comment]
You shouldn't be using this repo as the start for a project, rather just download the archived version from the website (https://html5boilerplate.com/), which basically is the contents of the "dist" folder: https://github.com/h5bp/html5-boilerplate/releases/download/5.2.0/html5-boilerplate_v5.2.0.zip

The dist version also doesn't come with any build tools, as the authors want to keep that outside of the scope of the boilerplate. You'd have to install and configure that yourself (with Grunt, Gulp, etc).

**Comment by stefek99** [comment]
OK. Thank you.

```src``` is for developers working on H5BP.

Regular user of H5BP should download official version from the website, potentially using a build tool to remove unwanted parts.

**Comment by TheDutchCoder** [comment]
Correct :-)

**Comment by atannerd** [comment]
I am new to this projects and this makes total sense.  However, I think it would be great to add to the documentation.  Tools like WebStorm just pull the whole repo and the documentation does not point you to the dist directory as a starting point.

I just saw the dist and src directories and assumed I should be using gulp.  That was fine until I got writing jQuery stuff and gulp failed.  I eventually came here but it was not obvious to me.

Just my 2 cents.

**Comment by roblarsen** [comment]
@atannerd We can update the docs to indicate that dist is where to look. It's a convention, but it can't hurt to point it out. I will say that WebStorm is doing it wrong if they're cloning the repo with the intent of it being consumed by a developer. running `npm install` would be preferable since that's designed to be just the files needed for a consumer.  

What are you doing within webstorm that it's cloning the repo? I've never used it.
