### ISSUE TITLE
Fix Chrome 44 issue on server to redirect to https.

### ISSUE THREAD

**Issue by proxyd** [h5bp/html5-boilerplate#1727]
With the release of Chrome Version 44.0.2403.89 m, I've noticed that our site is now completely broken. All of the HTTP URLs are being redirected to HTTPS URLs, which is a problem because our site does not support HTTPS.
```
<IfModule mod_headers.c>
  RequestHeader unset HTTPS
</IfModule>
```

**Comment by lucaspetter** [comment]
This is apparently a known issue with Chrome/Chromium, with a fix coming soon.
https://code.google.com/p/chromium/issues/detail?id=501842
https://code.google.com/p/chromium/issues/detail?id=505268

Your code does fix the problem, but can be removed once a Chrome update is released and users have had time to download it.

**Comment by arthurvr** [comment]
Can you reopen this at the [`apache-server-configs`](https://github.com/h5bp/server-configs-apache) repo?

**Comment by alrra** [comment]
> https://code.google.com/p/chromium/issues/detail?id=501842

`Status:  Fixed`
