### ISSUE TITLE
Regular files are executable in distribution

### ISSUE THREAD

**Issue by devinus** [h5bp/html5-boilerplate#1730]
<img width="551" alt="screen shot 2015-08-25 at 12 32 43 pm" src="https://cloud.githubusercontent.com/assets/4836/9474300/6accb2c8-4b25-11e5-9465-8f2770e3f614.png">

**Comment by alrra** [comment]
@devinus Thanks for opening this issue, and sorry for the delay!

Should be fixed by 97b04f4f4e62fc874d5dd0ea651b21f85294539e.
