### ISSUE TITLE
Override default hyperlink middle mouse click functionality

### ISSUE THREAD

**Issue by XtrmJosh** [h5bp/html5-boilerplate#1735]
It is widely accepted that the middle mouse button will open a given link in a new tab. Using h5bp, this is not the case. Observed primarily on the h5bp website, it seems middle mouse clicking links opens them in the current tab.

The environment I'm using currently is a Kubuntu desktop, running latest Chrome (45.0.2454.99). I can confirm, however that the issue reproduces in Firefox.

I don't use h5bp myself, however I noticed this issue on the "official website" (https://html5boilerplate.com/), which I assume uses h5bp. Feel free to disregard if this cannot be reproduced on a clean installation, and blame it on some other functionality of that website.

Steps to reproduce:
1. Visit https://html5boilerplate.com/
2. Middle click a hyperlink (one of the top 3 "SOURCE CODE", "DOCS", "OTHER PROJECTS" would do)
3. Observe link not opening in new tab

**Comment by quantumpacket** [comment]
@XtrmJosh This issue should have been opened on https://github.com/h5bp/html5boilerplate.com

**Comment by XtrmJosh** [comment]
Apologies, as I said I don't use this project. Are you able to confirm the issues presence on another h5bp installation? If so, this could more easily be closed and I could repost it over there, else, this issue probably stands.

**Comment by roblarsen** [comment]
@XtrmJosh It's not an issue with the core project. Quickly looking at the [source code](https://github.com/h5bp/html5boilerplate.com/blob/master/src/js/main.js#L62-L71) for the site there's specific code there to handle opening links in a new tab that fails to account for the middle mouse button.

**Comment by XtrmJosh** [comment]
Pretty narrow minded of you to assume that, really. Just because the code for opening links in a new tab doesn't contain anything regarding the middle mouse button, you assume that nothing else can? I assume at least one of you has an active installation of h5bp out there somewhere, that you could quite easily hop on just to see... Anyway, not my problem, just trying to be helpful.

Filed https://github.com/h5bp/html5boilerplate.com/issues/136 against the main website.

**Comment by roblarsen** [comment]
I'm not sure what you mean by "narrow minded?" I can read the source code at the site and have enough experience to triage that the issue is on the site and in those lines of code. I also have worked with dozens of "active installations" (including one of my biggest current projects) and haven't noticed this issue anywhere else. I've also been around this project since before it was public, so I'm pretty familiar with what it does and does not do.

**Comment by XtrmJosh** [comment]
Your implication was that because that particular bit of code doesn't contain anything that might modify middle click behaviour, it is not possible that the bug is related to this project. This is, from my view as a test engineer, very narrow minded.

**Comment by roblarsen** [comment]
Ah, I see. As I mentioned there's a lot more than just the two sentences I shared above involved in my ability to triage this issue (including having tested it against current projects I'm working on that are based on H5BP.)  The issue is now in the right place, so w're good. Thanks!
