### ISSUE TITLE
remove unnecessary reference to googleapis.com to stop page load failing in China etc

### ISSUE THREAD

**Issue by Jon007** [h5bp/html5-boilerplate#1737]
html5boilerplate.com. Version: 4.2.0
unnecessary script reference to googleapis.com causes boilerplate to fail (or load unbelievably slowly after timing out on the script) in China (500million internet users) and other countries where googleapis.com is blocked.
index.html contains:
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
since jquery is also included locally this line could be modified to:
        <script src="js/vendor/jquery-1.9.1.min.js"></script>
to avoid issues due to non-availability of googleapis.com

**Comment by coliff** [comment]
HTML5Boilerplate is currently on v5.2.0.
v4.x is no longer maintained or updated.

**Comment by roblarsen** [comment]
True, but the reference to [googleapis.com](https://github.com/h5bp/html5-boilerplate/blob/master/dist/index.html#L25) is alive and well so the issue is valid.

**Comment by roblarsen** [comment]
(When's the last time we talked about where we're loading jQuery from? Two years?)

**Comment by Jon007** [comment]
I think that was a typo, I was using 5.2.0.
I have tested the alternative CDNs listed on https://jquery.com/download/ and these all seem to be accessible from China without any tricks needed eg:
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
        <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>      
        <script src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.4.min.js"></script>   
        <script src="https://cdn.jsdelivr.net/jquery/2.1.4/jquery.min.js"></script>

**Comment by corvannoorloos** [comment]
I'm not really sure if h5bp should support any form of censorship. If else :+1: for `code.jquery.com`.
