### ISSUE TITLE
Add sample preload header for webfonts commented out in .htaccess

### ISSUE THREAD

**Issue by richbradshaw** [h5bp/html5-boilerplate#1738]
e.g.

    Link: <https://example.com/font.woff>; rel=preload; as=font

Maybe for google webfonts as an example, as they are common.

**Comment by QWp6t** [comment]
You should post this upstream: https://github.com/h5bp/server-configs-apache

See also: https://github.com/h5bp/html5-boilerplate/blob/master/CONTRIBUTING.md#using-the-issue-tracker
