### ISSUE TITLE
Modernizr 3.0

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#1740]
Modernisr 3.0 is out the door! Big round of applause! Awesome job!

H5BP is still running 2.8.3. This seems like a great time to take a look at the way Modernizr is used here. This is especially true since a lot of the activity on the Modernizr repo over the past few weeks is centering around getting people up and running with custom builds and (conversely) the idea of default builds.

So, hey! Discuss! What should the version of Modernizr that H5BP ships look like. Some standard set of detects? No detects at all? Does it ship Modernizr at all? Instead of a slimmed down Modernizr, why not just the HTML5shiv? What about a world with no IE8?

Related issues: #1605 (Move Modernizr to the bottom) and #1524 (Drop IE8 Support)

**Comment by alrra** [comment]
Cc: @patrickkettner

**Comment by JoshuaJones** [comment]
At the bare minimum level, I'd vote for the shivs (html5shiv & printshiv). A discussion of what falls into a "standard set" of detects will probably be a long back and forth.

**Comment by patrickkettner** [comment]
@JoshuaJones 
> I'd vote for the shivs (html5shiv & printshiv)

Just as an FYI - html5shiv is just the html5 shiv, but the printshiv is both the html5shiv and the printshiv. No reason for both.

**Comment by roblarsen** [comment]
Oh heck, I'm really serious about getting to zero issues and releasing a new version. Holy cow.

[I started a branch](https://github.com/roblarsen/html5-boilerplate/tree/modernizr) where I added a [config](https://github.com/roblarsen/html5-boilerplate/blob/modernizr/modernizr-config.json.) I took a stab at some interesting new tests (it felt most of the old ones aren't as interesting or useful anymore).  I'll add generating it t to the build task which will introduce our users to building it. Most people will still just use the default, but we will have an opportunity to educate along the way. Woo-hoo.

**Comment by roblarsen** [comment]
- [x] Add Modernizr config with new default tests
- [x] Build custom Modernizr with Gulp
- [x] Add tests for the file and for the correct path in `index.html`
- [x] Move Modernizr to the bottom

![nibali scores first stage win at tour 2014](https://cloud.githubusercontent.com/assets/361421/24487381/243bd752-14dd-11e7-9d26-940005611580.gif)

Here's the [branch](https://github.com/roblarsen/html5-boilerplate/tree/modernizr) I'd love feedback on the default tests. At this point that's the last thing I'm waiting on before creating a PR for this and closing two issues.
