### ISSUE TITLE
Print media query for img max-width breaks Google Maps printing in Chrome

### ISSUE THREAD

**Issue by rdlugosz** [h5bp/html5-boilerplate#1741]
Somewhat related to the issue with images in IE8 (https://github.com/h5bp/html5-boilerplate/issues/984), after a long search I've discovered that [line 260](https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css#L260) in the H5BP print media query breaks printing of Google Maps if your browser is too wide (or, more specifically, if the map div is wider than ~800px). I've seen this on several WebKit browsers; example below tested on Chrome 46.

The map will look fine on screen, but when you hit print you'll notice that all of the tiles are missing. I've created [a demonstration here](https://github.com/rdlugosz/h5bp-google-maps-issue/blob/master/index.html) . Note that the only file changed in this repo from the default H5BP install is index.html.

The simple fix is to override the style via:
```
@media print {
  img {
    max-width: none !important;
  }
}
```

... but this took me a rather long time to discover (on and off for weeks until finally digging in with process of elimination). Is there a reason why this style is being set?

It strikes me that this could be considered a Google Maps bug and not that of H5BP, but thought this would be a better place to start. After all, a stock browser does not exhibit this problem until H5BP is introduced.

**Comment by cvrebert** [comment]
X-Ref: https://github.com/twbs/bootstrap/issues/1506

**Comment by rdlugosz** [comment]
Is that bug really related? This is specifically related to the print styles, not the regular img display.

**Comment by cvrebert** [comment]
Same underlying issue, which is that `img { max-width: 100%; }` isn't compatible with Google Maps (among other widgets, e.g. Mapbox). The only difference is that in h5bp the problematic CSS is within a print media query.

**Comment by alrra** [comment]
>  Is there a reason why this style is being set?

@rdlugosz It was [introduced](https://github.com/h5bp/html5-boilerplate/commit/b2faa1fc3cff20568848c98e9a51ecda61f3bf73) in order to  prevent images from getting cut off on print.

**Comment by rdlugosz** [comment]
That's reasonable, but while it fixes a problem with images being cut off,
it creates an arguably more unexpected result with several mapping systems.

Any thoughts on how this could be adapted to solve the basic image problem
while not impacting the way the mapping frameworks work?

Or, would this be better resolved via a readme or FAQ item?

**Comment by QWp6t** [comment]
Just read the solution in the link @cvrebert posted.

```css
img[src^="http://maps.gstatic.com/"], /* map view */
img[src^="http://maps.googleapis.com/"] /* street view */
{
  max-width: none !important;
}
```

**Comment by cvrebert** [comment]
s/the solution/a mediocre solution/

**Comment by paulirish** [comment]
If it's good enough for bootstrap, then why not.  :)

Open to a PR like https://github.com/twbs/bootstrap/issues/19000
