### ISSUE TITLE
Ending oldIE support?

### ISSUE THREAD

**Issue by AllThingsSmitty** [h5bp/html5-boilerplate#1743]
Support is currently provided for IE8+. Microsoft support for IE < v.11 [ends on January 12, 2016](https://technet.microsoft.com/en-us/ie/mt163707). Should we be now talking about eliminating some much older versions of IE from support, e.g., IE8-9 or more?

**Comment by AllThingsSmitty** [comment]
Similar discussion on IE9 [issue 1688](https://github.com/h5bp/html5-boilerplate/issues/1688).

**Comment by alrra** [comment]
@AllThingsSmitty See: #1524.
