### ISSUE TITLE
Support for Microsoft Edge browser

### ISSUE THREAD

**Issue by AllThingsSmitty** [h5bp/html5-boilerplate#1744]
Is H5BP supported on Edge, Microsoft's post-IE-era browser? I don't see it listed so maybe it's just an oversight in the documentation.

**Comment by patrickkettner** [comment]
Yes.

**Comment by AllThingsSmitty** [comment]
PR https://github.com/h5bp/html5-boilerplate/pull/1745 submitted.

**Comment by FagnerMartinsBrack** [comment]
> Is H5BP supported on Edge, Microsoft's post-IE-era browser?

The guys behind Microsoft Edge states that "if it works in Firefox and it works in Chrome, then it should work in edge". That's a good reason to consider it as implicitly supported.
