### ISSUE TITLE
Defining an "outdated" browser

### ISSUE THREAD

**Issue by JohnnyWalkerDesign** [h5bp/html5-boilerplate#1747]
At present Boilerplate defines "Outdated" as being **before** Internet Explorer 8. As IE 11 is available for Windows 7 and above, I would personally contend that anything below IE 11 is "Outdated", but I would like hear what other people think.

I do think that describing IE8 as a "modern" browser is a too generous :) 

Thanks for any feedback.

**Comment by roblarsen** [comment]
Crossing the #1524 barrier is going to be the start of this discussion.

**Comment by JohnnyWalkerDesign** [comment]
Hi Rob, thanks for your comment. I'm not discussing what browsers Boilerplate should support, I'm just discussing when the user should be told they're using an outdated browser.

**Comment by roblarsen** [comment]
I understand your intent. I'm just pointing out that this discussion is dependent on the more practical browser support issue. If H5BP drops support for IE8 then that part of the discussion is sorted out automatically.

**Comment by JohnnyWalkerDesign** [comment]
Hi Rob, I think you're missing the point entirely. This is not about developers and what kind of support they can expect from Boilerplate, this is about users and when they should be informed they're using an "Outdated" browser. The two are completely unrelated. The question is about how you define "Outdated".

Thanks for commenting.

**Comment by Grandt** [comment]
Actually, as of next week (January 12) all IE versions older than 11 will be retired and receive no further updates. I think it'll be a good idea to emphasize this.

In short, as of next Tuesday IE < 11 must be considered unsafe, and sadly some users need to get that hammered into their heads with out-sized railroad spikes to get the message.

H5BP should help.

Ref: https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support

Replace the current test with something slightly over the top:

**Comment by rejas** [comment]
I think they removed conditional comments from IE10 onwards: https://msdn.microsoft.com/en-us/library/hh801214%28v=vs.85%29.aspx

**Comment by JohnnyWalkerDesign** [comment]
It's true. Everything before IE11 is now even more outdated:

`<!--[if IE]>` is all that's required.

**Comment by nosilleg** [comment]
@Grandt This is not true.  There are 3 supported versions of IE.  (9-11)  See the table here: https://blogs.msdn.microsoft.com/ie/2014/08/07/stay-up-to-date-with-internet-explorer/

There was a policy change, from "we support the version of IE that originally shipped with supported OS's" to "we only support the latest version of IE for supported OS's".  But there are lots of people who have taken that to mean IE<11 is unsupported, which is incorrect.

**Comment by patrickkettner** [comment]
its more or less correct. IE 10 is only supported on a specific version of windows server. IE 9 is only supported on vista, and server 2008. That means for ~98-99% of windows users, it is ie11+

**Comment by Grandt** [comment]
@nosilleg Fair enough, I fell for that as well it seems. But as @patrickkettner also mentions, the number of platforms locked to IE < 11 as very few, and probably covers a very small number of users. I think it'd be the right thing to do to remind these few users that there are alternatives. A semi-static gray line at the top of the page would serve that purpose as it's fairly unobtrusive. 

Then again, this is "just" a boilerplate. I say, implement the notifications for IE < 11, with some guidelines in the HTML comment for it, essentially give the developers using the boilerplate the option to comment it out if they don't want it.

**Comment by nosilleg** [comment]
@patrickkettner It isn't correct.  A decision can be made to not care about the minority who use those platforms, but to say that are not supported versions of IE is not factual.

And "~98-99% of windows users" should be "~98-99% of users using supported versions of Windows *should* be using IE 11", but that doesn't mean that they are using IE 11, and excludes all those using unsupported versions of Windows.

But yes, this could just be nit-picking on my part.

**Comment by WebNinjrDesign** [comment]
@Grandt I think it makes sense to leave the HTML in the HTML, and not take it out into the JS., unless there is good reason to, also, for those crazy few that don't have JS active...which is probably 0%, but still.

**Comment by JohnnyWalkerDesign** [comment]
@nosilleg Yes, I think you're right that this is nitpicking. There are three exceptions to the notion that IE 11 is now the only officially supported version if IE: Users on Vista SP2, Windows Server 2008 R2, or Windows Server 2012 (but not R2). 

Let's go through them: Firstly, Windows Vista's support cycle ends later this year. Windows Server 2008 R2's support cycle ended last year. This means there's only one exception: Developers building websites for users who are using Windows Server 2012 as their operating system. 

To suggest this is anywhere near 2% of the people surfing the Internet is absurd. 

It is now de facto advice to advise users to upgrade to IE11 or switch browsers.

**Comment by nosilleg** [comment]
@johnnywalkerdesign 

Now your nitpicking. Change the copied % to "near 100%" and the point is still valid.

Fact: there are three supported versions of Internet Explorer.

Opinion: we don't care about people not on IE11.
Opinion: it's OK to tell people on Vista that the latest version of IE for Vista is unsupported.

But this ticket isn't about unsupported, it's about "outdated". Outdated compared to what? The latest supported version of that browser for your OS? Outdated compared to a version of your browser that you can't even get on your OS? Outdated compared to other browsers that you can get on your OS?

Those are all opinion answers that are fair game for this discussion. Saying only IE 11 is supported is not. It is factually incorrect. Usually a factually incorrect statement to prop up an opinion about what is "outdated" isn't very honest.

**Comment by JohnnyWalkerDesign** [comment]
Where did I say that IE11 is the only supported version of IE?

**Comment by JohnnyWalkerDesign** [comment]
Where did I say that IE11 is the only supported version of IE?

**Comment by nosilleg** [comment]
If you consider 16 months to be "a few months". The date I see for end of support is 11 April 2017.

I would have presumed that your opinion statement "It is now de facto advice to upgrade < IE11 to IE11 or switch browsers." would mean telling people on Vista that they shouldn't be using their supported browser any longer. But, yes, you could word that without using the word "unsupported".  Those were example opinions, BTW, not an attack on you.

**Comment by JohnnyWalkerDesign** [comment]
Mainstream support ends in October of this year, but you're right that barebones Extended support will continue a few months to April. This is all moot, however, as it just comes down to where Windows Vista/IE9 are "outdated" bits of software. I think Microsoft would say they were, even though they have a support policy that supports them for a while longer.

Do you really think they're not outdated, or are you just playing devil's advocate?

**Comment by nosilleg** [comment]
I only commented to say that there are 3 supporter versions of IE. I'm not contributing to the opinions about what is outdated. For me it doesn't matter what opinion gets used in the boilerplate since the projects I work on will have their own opinions and things will be updated accordingly.

**Comment by alrra** [comment]
Closing in favor #1748 (and also #1524).
