### ISSUE TITLE
Fallback problem

### ISSUE THREAD

**Issue by ademsenel** [h5bp/html5-boilerplate#1762]
I tried to made MVC project by Boilerplate template 
but i saw something wrong went i apologize to send those issues 
First issue is fallback problem when i used cdn for budling but its always using local files of css and js.
and when i removed them from local it doesn't work.
Second i saw that if java scripts is disabled how it will able to connect fallback options because it was written by java

**Comment by NoelDavies** [comment]
Can you please provide a screenshot and\or debug output from a console?

**Comment by ademsenel** [comment]
Hi 
I see what is problem I was configure debug true in web.config
but the template need BundleTable.EnableOptimizations is true then it was work correctly 
thank you
