### ISSUE TITLE
meta description length limit for Google SERP

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1767]
For the Description meta tag to have the best effect in Google search results pages, limit the content to about 143 characters.

The number has to be approximate to accommodate font proportionality.

This should be added to extend.md > Search, with a new subsection, Description Meta Tag.

**Comment by alrra** [comment]
> limit the content to about 143 characters.

@Nick-Levinson Please provide official link. Thanks!

**Comment by Nick-Levinson** [comment]
None known or claimed. I found out through trial and error.

It's possible that websites programmed to support Rich Snippets or showing an icon in or with Google's snippet do better with a different number.
