### ISSUE TITLE
blocking Google bot via robots.txt inadequate against backlinked page, should use meta tag or HTTP header

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1769]
For pages to be excluded from Google search results, adding the robots noindex meta tag to that page or an X-Robots-Tag HTTP header would be more exclusionary than a page-specific directive in robots.txt because backlinks might lead to inclusion and disallowing in robots.txt will prevent Google from knowing of the meta tag. [Disallowing and not disappearing from Google search results](https://developers.google.com/webmasters/control-crawl-index/docs/faq?hl=en#h17). The effect on other search engines is unknown.

I suggest adding the above to extend.md > Search, as a new subsection, Robots meta tag.

The URL was last accessed by me Dec. 25, 2015.

**Comment by alrra** [comment]
@Nick-Levinson Feel free to open a [pull request](https://github.com/h5bp/html5-boilerplate/blob/d35a8e902046bd77576b37039298e5206f9e3b90/CONTRIBUTING.md#pull-requests)!

**Comment by Nick-Levinson** [comment]
Thank you, but I found out for another issue that doing so would probably take a few hours to learn and carry out, assuming I have the software for it, and I'm moderately geeky. I'll leave this as a suggestion for anyone else to act on or not. Thanks again.
