### ISSUE TITLE
Yahoo search engine bot can be blocked from indexing page parts

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1770]
If part of a Web page should not be indexed by Yahoo's search bot, this is a method offered by Yahoo:

&lt;div class="robots-nocontent"&gt;Don't index this text.&lt;/div&gt;

Source: https://help.yahoo.com/kb/search/meta-tags-robotstxt-yahoo-search-sln2213.html > Prevent Specific Content From Being Indexed, as accessed Dec. 25, 2015.

A limit is that Yahoo gets only some of its information from its own crawler, as it also uses info from Bing and Bing might index the content. But it might be worth trying anyway, in case Yahoo rejects info from Bing that contradicts info it already has, such as Yahoo's decision not to index.

Whether Yahoo will recognize the class if applied to an element other than a div is unknown. That's open to experimentation.

I like to classify elements by a convention (my own) that's easier for me to parse regarding page organization, so I would probably assign more than one class or would enclose one div within another.

This should be added to extend.md > Search > Hide Pages From Search Engines, or a separate subsection, perhaps titled Hide parts of pages from search engines, should be added to the Search section.

**Comment by Nick-Levinson** [comment]
Sorry about my inclarity; recoding the symbols for the classified div element fixed it.

**Comment by Garbee** [comment]
imo this starts getting into a whole sublevel of SEO that most developers won't encounter or have the need to apply.

**Comment by Nick-Levinson** [comment]
Wasn't intending to add SEO (that's too huge a field for H5BP to describe), only to address that H5BP already covers hiding pages from search engines and add to that kind of info.
