### ISSUE TITLE
add URL for Apache docs

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1772]
In misc.md > Server Configuration, the penultimate paragraph, where you give a URL for more information on <.htaccess>, you should also cite <http://httpd.apache.org/docs/>. The present URL links to the latter through a breadcrumb but I think it should be more obvious.

**Comment by roblarsen** [comment]
This would be a really easy  PR for someone.

**Comment by lowellmower** [comment]
@Nick-Levinson was [this](https://github.com/h5bp/html5-boilerplate/pull/1774) what you were thinking?

**Comment by Nick-Levinson** [comment]
Looks good all around. Thank you.
