### ISSUE TITLE
Replace CSS clip property with clip-path

### ISSUE THREAD

**Issue by twittkopf** [h5bp/html5-boilerplate#1775]
The CSS `clip` property has been deprecated in favor of `clip-path`, but the [current version of H5BP is still using `clip`](https://github.com/h5bp/html5-boilerplate/blob/v5.0.0/dist/css/main.css#L135). Maybe it's time for a small update? Not sure about browser support though.

This change was already mentioned back in 2012 in #1247, but has been closed because it wasn't clear at that time if there are any consequences in using `clip`. Although I am not aware of any, I still think it's a good idea to stick to the spec with using `clip-path` instead of `clip`.

Reference:
http://www.w3.org/TR/css-masking/#the-clip-path
https://developer.mozilla.org/en-US/docs/Web/CSS/clip
https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path

**Comment by ltodorov** [comment]
Although it is added to the RC it is not supported well. Ref. http://caniuse.com/#feat=css-clip-path

**Comment by paulirish** [comment]
closing until the browser support is there.
