### ISSUE TITLE
where to report some H5BP issues

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1776]
Some H5BP issues should get reported elsewhere than here. That should be stated earlier in the process. On the H5BP home page (https://html5boilerplate.com/) just one link points to a place for issues, the link text being "Report issues", presumably meant for all issues for all parts of H5BP. But since that's probably not the case (at least for .htaccess and normalize.css), some statement should redirect us. This could be the H5BP home page, &lt;https://github.com/h5bp/html5-boilerplate/issues&gt;, or an intermediate page on either website that separates issues by destination for reporting.

**Comment by alrra** [comment]
> That should be stated earlier in the process. 

@Nick-Levinson When a user opens an issue, GitHub informs her/him that she/he [should read the contributing guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) (namely, the [`CONTRIBUTING.md`](https://github.com/h5bp/html5-boilerplate/blob/4b089a3a76754d6fbef5bb630d797c508f7aee7c/CONTRIBUTING.md#using-the-issue-tracker) file).

![screen shot 2016-01-10 at 23 22 24](https://cloud.githubusercontent.com/assets/1223565/12224868/b3e43bd4-b803-11e5-9f37-b550a375fd82.png)

However, that doesn't usually help. Neither does having the information in the [`README.md`](https://github.com/h5bp/html5-boilerplate/tree/4b089a3a76754d6fbef5bb630d797c508f7aee7c#contributing), and IMHO, neither will having it again on the site. 

GitHub made the process of opening issues very easy, and as a consequence, no matter in how many place the contributing guidelines will be, a lot of people will still ignore them.

> H5BP home page

Note that: quite a lot of users don't end up to this GitHub repository from the site.

--

See also: 

  * discussion about why the [Babel](https://github.com/babel/babel) team [decided to not used GitHub issues anymore](https://www.youtube.com/watch?v=1w_W5cd8qRE&t=39m54s)
  * Jacob Thornton's talk: [_"What Is Open Source & Why Do I Feel So Guilty?"_](https://www.youtube.com/watch?v=UIDb6VBO9os&t=19m50s)

**Comment by Nick-Levinson** [comment]
For a footnote, at least I read or skim rules and guidelines for posting when I first join a site, usually finding that they say standard things like be clear and don't spam, and then almost never read them again for the same sites. So when I have been using a site a while and then it occurs to me to do something different, I may not remember that the rules/guidelines had an exception for that. Oh, and I also read or skim terms of use and other legal gobbledygook like it's a snack. I suspect most lawyers don't. Like someone said about apps, a manual is a list of what's wrong with an app, and it's often more productive to design a UI to fit what users do in practice, where possible.

I didn't play the audios. I'd rather read, but I guess that's not an option with these and I didn't find equivalents online by these speakers. Thanks for the links.
