### ISSUE TITLE
Remove crossdomain.xml

### ISSUE THREAD

**Issue by frontenddeveloping** [h5bp/html5-boilerplate#1779]
Browsers disabled flash by reason of it secuire problems (but enabled it after fixes). Note sure that it still nessesary.
Let's push browser native capabilities, not plugins.

**Comment by paulirish** [comment]
sure. sounds good. it's probably time.

anyone wanna file a PR for this?

**Comment by roblarsen** [comment]
closed via #1881

**Comment by BobbyBabes** [comment]
`crossdomain.xml` is still in the v5.3.0 download here at GitHub in `Releases`, and under the orange download button at http://html5boilerplate.com

**Comment by roblarsen** [comment]
We haven't done a release, unfortunately.

**Comment by BobbyBabes** [comment]
OK, that explains it then.
