### ISSUE TITLE
Discussion: Adjust meta viewport to enable GPU rasterization in Chrome for Android

### ISSUE THREAD

**Issue by steffenweber** [h5bp/html5-boilerplate#1784]
According to https://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization, GPU rasterization in Chrome for Android requires `minimum-scale=1`.

I've checked this in Chrome for Android 48: Go to `chrome://flags` and enable "FPS counter". After a restart, you'll see a "Frame Rate" overlay with a "GPU Raster" entry. Its value is either "off (viewport)" or "on" depending on the existence of `minimum-scale=1` in the viewport meta tag.

Found this here: https://github.com/ampproject/amphtml/issues/592

This furthermore solves the following strange issue on a Moto G3: https://code.google.com/p/chromium/issues/detail?id=519996

HTML5 Boilerplate currently uses:
`<meta name="viewport" content="width=device-width, initial-scale=1">`

Maybe this should be changed to:
`<meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1">`

**Comment by paulirish** [comment]
The chromium team is removing the requirement of "minimum-scale". I'd prefer we wait on that.

(I sit 30 feet away from the engineers who are working on GPU rasterization so that's why i'm taking this position. But generally these sorts of improvements are completely awesome and what h5bp is all about. so thanks for writing the issue)

**Comment by dminkovsky** [comment]
Early 2020: can we assume minimum-scale has been removed as a requirement?

**Comment by steffenweber** [comment]
According to https://www.chromium.org/developers/design-documents/chromium-graphics/how-to-get-gpu-rasterization, it's no longer a requirement since Chrome on Android version >= 54.

**Comment by dminkovsky** [comment]
Oh yes, you're right, it does say it clearly right there:

> How to enable GPU rasterization: ... Chrome on Android version >= 54 ... Any viewport definition will work.

For desktop, it looks like only Linux is still being worked on: https://bugs.chromium.org/p/chromium/issues/detail?id=419521#c25

Thank you!
