### ISSUE TITLE
index.html Analytics script should not be supplied verbatim

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1790]
H5BP v5.3.0's index.html provides the text of a Google Analytics script for us to copy subject to changing only the UA number. But Google recommends other edits to the script (at least for enhanced link attribution (see https://support.google.com/analytics/answer/2558867?hl=en and <https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-link-attribution>, both as accessed Feb. 6, 2016)). If they've been implemented and forgotten, copying H5BP's version of the script would lose those edits in a production site. The editing may have been a long time ago and is undocumented in the normal script, and so may be forgotten. In addition, your version of the script and the one I downloaded fairly recently for my site (cold32.com) are different in several other ways, including a possibly more fundamental way: compare, near the beginnings, "b,o,i,l,e,r" and "i,s,o,g,r,a,m", respectively (and cf. "t,e,a,n,o,i" in the home page of html5boilerplate.com, as accessed Feb. 6, 2016). Therefore, H5BP should either omit the script and only talk about it (e.g., link to Google's documentation about it) or should acknowledge that any other edits besides to the UA number should also be preserved, focusing on the placement of the whole script within the HTML as the subject of H5BP's treatment.

**Comment by jpdevries** [comment]
I'm noticing that when using either h5bp style or google analytics style tracking code Google PageSpeed Insights punishes me. This is ironic isn't? Is there anything other than using a lengthy setTimeout that can be done to not be punished for using Google analytics? Why doesn't Google set the expiry date for more than 2 hours for the ga script? 
https://twitter.com/mrktps/status/714045951892185090

![](http://j4p.us/322m0S413m44/Screen%20Shot%202016-03-27%20at%201.29.48%20PM.png)
