### ISSUE TITLE
Add shrink-to-fit to viewport meta tag

### ISSUE THREAD

**Issue by ireade** [h5bp/html5-boilerplate#1815]
For responsive websites to be compatible with Safari in Split View, Apple recommends the addition of "shrink-to-fit=no" to the viewport meta tag ([See iOS 9.1 doc](https://developer.apple.com/library/mac/releasenotes/General/WhatsNewInSafari/Articles/Safari_9_1.html))

```
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">  
```

[An article on why shrink-to-fit was added](http://bitsofco.de/ios-safari-and-shrink-to-fit/)

May I submit a PR with this addition?

**Comment by paulirish** [comment]
AFAICT, it was added because people were using `width=device-width, initial-scale=1` without understanding what they do.

my concern is that having shrink-to-fit in here would end up with the same result.

**Comment by WarenGonzaga** [comment]
got a good point!
