### ISSUE TITLE
Visuallyhidden class and high contrast 

### ISSUE THREAD

**Issue by martinbethann** [h5bp/html5-boilerplate#1822]
The **visuallyhidden** class appears to be an accessibility issue for users using high contrast modes.

"Use JavaScript to detect when images are disabled and remove the CSS visually hidden display state of the text alternative.
Use JavaScript to detect when Windows high contrast mode is enabled and remove the CSS visually hidden display state of the text alternative."
-https://www.paciellogroup.com/blog/2012/08/notes-on-accessible-css-image-sprites/

Is this a valid point and if so, should the javascript used to correct this issue be added to the boilerplate?

Thanks.

**Comment by roblarsen** [comment]
At the very least this should be added to the documentation.

**Comment by roblarsen** [comment]
I'm going to add this to the docs
