### ISSUE TITLE
.htaccess config issues

### ISSUE THREAD

**Issue by dvLden** [h5bp/html5-boilerplate#1829]
If there's a case with an website that is using these two combined:

---

_Suppressing / Forcing the `www.` at the beginning of URLs_
(personally using Option 1: rewrite www.example.com → example.com)
_Forcing `https://`_

---

If we type in URL something like:
http://domain.com → Result: https://domain.com

But if we type:
http://www.domain.com or just www.domain.com → Result: https://www.domain.com
So that will fail, as we probably don't have https on both www and no www.

If we move the rule _Forcing `https://`_ below the rule _Suppressing / Forcing the `www.` at the beginning of URLs_ then it will work fine.

**Comment by himanshu81494** [comment]
Hi,
I am new here and want to contribute.
Can I submit a pull request with changes you suggested here

**Comment by yahreen** [comment]
+1

**Comment by dvLden** [comment]
@himanshu81494 - Sure if you want to...

**Comment by hatzopoulos** [comment]
See https://github.com/h5bp/server-configs-apache/issues/52

**Comment by paulirish** [comment]
closing to defer to h5bp/server-configs-apache#52
