### ISSUE TITLE
Print pages in IE11

### ISSUE THREAD

**Issue by Daveloose** [h5bp/html5-boilerplate#1832]
When printing a HTML5 boilerplate page IE11 crashes (print preview also fails).
You can fix it by removing the following lines:
`*,
    *:before,
    *:after,
    *:first-letter,
    *:first-line {
        background: transparent !important;
        color: #000 !important; /* Black prints faster:
                                   http://www.sanbeiji.com/archives/953 */
        box-shadow: none !important;
        text-shadow: none !important;
    }`

## Step to reproduce:
1. Download HTML5 boilerplate
2. Open in IE11
3. Try to print (it's not working - I don't even get the print dialog box)

**Comment by slavanga** [comment]
This has already been reported.
See: https://github.com/h5bp/html5-boilerplate/pull/1799

**Comment by roblarsen** [comment]
Fixed in #1799
