### ISSUE TITLE
Adding inline-block class helper?

### ISSUE THREAD

**Issue by adelivuk** [h5bp/html5-boilerplate#1838]
As there is a [`.clearfix`](https://github.com/h5bp/html5-boilerplate/blob/master/src/css/main.css#L171) helper class for floated elements, how about adding some helper class also for `inline-block` elements and it's [whitespace issue](http://stackoverflow.com/questions/5078239/how-to-remove-the-space-between-inline-block-elements)?

As [rem](http://caniuse.com/#feat=rem) has good support, we can use it:

    html{
        font-size: 1em;
    }

    .ib-parent{           /* ib -> inline-block */
        font-size: 0;
    }

    .ib-child{
        font-size: 1rem;
        display: inline-block;
    }

Which doesn't use those _ugly_ HTML comments.

**Comment by paulirish** [comment]
thanks for the suggestion. Lots of helpers could be created but it's hard to pick the right ones. 

Unfortunately i don't think this one will have the consensus that it's as critical as the others in there.
Cheers
