### ISSUE TITLE
suggest catching traffic sent to unused mobile subdomains and directories

### ISSUE THREAD

**Issue by Nick-Levinson** [h5bp/html5-boilerplate#1839]
If a website does not use the following subdomains for a mobile site or other use, it probably should set up aliases for them to the parent domain in order to catch traffic some users' devices might automatically send there:

i.* ---
--- except sometimes used for images
--- per https://i.reddit.com/ & https://www.reddit.com/r/web_design/comments/i1h0a/is_there_a_standard_url_for_mobile_versions_of/
--- --- comment by kataire
--- --- used by iOS (not confirmed or disputed at apple.com but I may have missed something at that site and I don't have iOS or Safari)
--- per https://wordpress.org/support/topic/mobile-redirect

mobi.* ---
--- apparently both from same book but I didn't read much context although apparently relevant:
--- --- per https://books.google.com/books?id=dNvXnUz-pwwC&pg=PA626&lpg=PA626&dq=%28%22i.example.com%22+OR+%22mobi.example.com%22%29&source=bl&ots=O0RnwEfR3Y&sig=USmI4u7UZqDOI5Tfk3sNJJFAric&hl=en&sa=X&ved=0ahUKEwim3oaYwafMAhWTCD4KHTj7BHgQ6AEIJzAC#v=onepage&q=%28%22i.example.com%22%20OR%20%22mobi.example.com%22%29&f=false
--- --- per https://www.safaribooksonline.com/library/view/css-cookbook-3rd/9781449377250/ch14s04.html

mobile.* ---
--- per https://wordpress.org/support/topic/mobile-re-direct-godaddy-to-dudamobile-not-working

All accesses to the above URLs were on Apr. 24, 2016.

I also redirect from /i and /mobi and /mobile in <.htaccess>, although I forgot where something like that was suggested previously. I thought it was recommended in the H5BP package but maybe not.

**Comment by quantumpacket** [comment]
Just wanted to add `m.*` and `/m` as well. However the URL redirects I'd be really hesitant on as those are more likely to conflict with actual pages. For example Acme Corp may offer a mobile app and they may use `/mobile` for the product page, which is common. That being the case it may not be best to have that in core, but rather in the docs.
