### ISSUE TITLE
X-UA-Compatible meta tag or htaccess

### ISSUE THREAD

**Issue by Inspirons** [h5bp/html5-boilerplate#1861]
Hello.
1. Why in the assembly H5BP used immediately and meta tag X-UA-Compatible and rule htaccess?
2. Is it better to use a meta tag X-UA-Compatible or rule htaccess?
3. Why not counted chrome = 1, for example <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> ?
4. What better implementation H5BP or https://www.drupal.org/files/issues/htaccess_23.txt?

**Comment by quantumpacket** [comment]
Not understanding all what you're asking.  But for point 2, it's better to use a meta tag in the boilerplate as not everyone has access to set headers. For example: front-end devs who don't have back-end access, really weird providers that don't support setting headers (trust me they are out there), and some proxies will strip out the header. I'm sure there may be other possible reasons as well.

A meta tag solves these scenarios. But it's all up to the developer to decide which method is best for them, and within their capabilities. :)

**Comment by Inspirons** [comment]
I am sorry if it is not clear writing.
I'm Russian, so it's hard to write.

**Comment by Inspirons** [comment]
on the third item:
H5BP why not apply the chrome=1
for example
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

**Comment by quantumpacket** [comment]
@Inspirons 

See: https://blog.chromium.org/2013/06/retiring-chrome-frame.html and https://github.com/h5bp/html5-boilerplate/pull/1396 in regards to `chrome=1`.

**Comment by paulirish** [comment]
> 1. Why in the assembly H5BP used immediately and meta tag X-UA-Compatible and rule htaccess?

because some people dont use the apache config, so its duplicated

2. Is it better to use a meta tag X-UA-Compatible or rule htaccess?

better in htaccess probably. as long as its only sent for HTML

> 3. Why not counted chrome = 1, for example <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> ?

chromeframe is dead.

4. What better implementation H5BP or https://www.drupal.org/files/issues/htaccess_23.txt?

h5bp. ;)
