### ISSUE TITLE
W3c compliance and nested comments around HTML tag

### ISSUE THREAD

**Issue by noise-cd** [h5bp/html5-boilerplate#1871]
I have been running some tests today and seems using nested comments now breaks w3c validation. Does anyone have a nice solution?

```
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
```

Error: Saw ↩<html class=

**Comment by roblarsen** [comment]
Remove the conditional comments OR don't worry about W3C validation.

**Comment by mathiasbynens** [comment]
Ref. #1631.

**Comment by jeremykohn** [comment]
I just tried it in https://validator.w3.org/nu/#textarea and it seems to work. It only needs a non-empty `<title>` element.

**Comment by paulirish** [comment]
Latest h5bp doesn't even have these any longer. Also what rob, mathias and jeremy said.

Closing :)
