### ISSUE TITLE
Root files

### ISSUE THREAD

**Issue by szepeviktor** [h5bp/html5-boilerplate#1875]
Maybe some of you are not involved in $10k projects, so I've started this repo
https://github.com/szepeviktor/RootFiles
to automatically generate files in the document root which get downloaded without links.

**Comment by QWp6t** [comment]
That ... looks very messy. But if it works for you, then more power to ya.

Not exactly a h5bp issue, though. :confused:

**Comment by szepeviktor** [comment]
Actually I am just brainstorming.

**Comment by szepeviktor** [comment]
@QWp6t Your comment made me rethink the project
https://github.com/szepeviktor/RootFiles
Please take a look at it and comment again.
Thanks!
