### ISSUE TITLE
Get a custom build（www.initializr.com）无法访问此网站

### ISSUE THREAD

**Issue by helloqingfeng** [h5bp/html5-boilerplate#1877]
无法访问此网站
www.initializr.com 的响应时间过长。
请在 Google 中搜索“initializr”
![360 20160722012041141](https://cloud.githubusercontent.com/assets/9712785/17032188/893abe1e-4faa-11e6-8ebe-f3062c3641b1.jpg)

**Comment by tjwudi** [comment]
这个代码仓库中请用英文沟通(Please use English).
