### ISSUE TITLE
Help Wanted (was: Closing greenkeeper PRs)

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5-boilerplate#1880]
FYI I'm closing a bunch of the open greenkeeper PRs

None are particularly unwanted, but I'd rather not have them pile up when we can't afford the time to land them.
#1870, #1869, #1868, #1867, #1864, #1855, #1854, #1853, #1852, #1851, #1850, #1849, #1848, #1847, #1846, #1844, #1843, #1842, #1840, #1837, #1836, #1835, #1833, #1831, #1830, #1827, #1826, #1825, #1824, #1823, #1821, #1818, #1817, #1816, #1813, #1812

FYI If anyone is interested in helping to assess issues and land PRs, please get in touch. We're a bit behind lately and could use some help. Cheers

**Comment by battaglr** [comment]
@paulirish, let me know if I can be of any help. 😀

**Comment by paulirish** [comment]
@battaglr sounds good. eager for some help getting issues and PRs to a conclusion. (basically what i was just trying to do on all those issues (sorry for the email everyone!))

if that is looking good and you're getting items ready to merge/close then email me and I'll make sure you have permissions here.

IMO first priority would be getting the manifest.json set up. :)

**Comment by coliff** [comment]
@paulirish I'd love to get involved more and help assess issues and land PRs etc.

**Comment by roblarsen** [comment]
@paulirish  I'll actually have some time from now(ish) through the fall to help out.

**Comment by paulirish** [comment]
most good. Thanks guys. 

@roblarsen you're very obviously welcome to help out whenever you have time. appreciate your help over the years here. just gave you write permissions for the repo.

**Comment by caraya** [comment]
I'd love to help if needed

**Comment by roblarsen** [comment]
So, the good news is that I had a bit more time to help out beyond fall 2016.  The bad news is that I am going to be very busy very soon and won't be able to devote any time to this project for at least a couple of months. **The thing is** I'd really like to release version 6.0 so if anyone has the time and inclination to help out we'd love to hear from you!

**Comment by roblarsen** [comment]
We'll add another help wanted note to the site with 6.0
