### ISSUE TITLE
Consider adding rel=noopener

### ISSUE THREAD

**Issue by h0r0man** [h5bp/html5-boilerplate#1893]
According to [rel-noopener](https://mathiasbynens.github.io/rel-noopener/) by @mathiasbynens, it seems to be very important. How about to consider implement `rel=noopener` to h5bp?

**Comment by mathiasbynens** [comment]
No; instead, we shouldn’t add `target=_blank` to anchors.

**Comment by h0r0man** [comment]
@mathiasbynens So basically when you add `target=_blank` then is preferred to add `rel=noopener`?

**Comment by mathiasbynens** [comment]
@h0r0man Yep. Actually, it’s preferred to not use `target=_blank` at all, since there is seldom a good reason to.
