### ISSUE TITLE
a tag inside span is valid ?

### ISSUE THREAD

**Issue by monochrome-yeh** [h5bp/html5-boilerplate#1894]
a tag inside span is valid ?

for example:

```html
<span>
    <a href="#">a tag inside span</a>
</span>
```

```html
<span>
    <a href="#" style="display:inline-block">a tag inside span</a>
</span>
```

I would like to know we usually use `a` to contain the others inline elements even them are block element, but if it's a `span` ?

**Comment by pzi** [comment]
Nothing wrong with having an `a` HTML Element inside a `span` HTML Element. It is valid, as you can test for yourself using the [text input of the w3 html checker](https://validator.w3.org/nu/#textarea).

**Comment by roblarsen** [comment]
@monochrome-yeh This isn't an HTML5 Boilerplate issue so I'm closing. This issue tracker is for bug reports, features requests and submitting pull requests specific to this project. 

That said, good luck learning about HTML usage and thanks @pzl for offering up your answer.
