### ISSUE TITLE
jQuery local fallback: Chrome will no longer load scripts via document.write over slow connections 

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#1896]
via @jpdevries in a comment on [1039](https://github.com/h5bp/html5-boilerplate/pull/1039#issuecomment-245438921)

> Speaking of the document.write() fallback (which I think rules) what about this?
> 
> > Chrome will no longer load scripts that are inserted via document.write() when net connection is slow
> > https://developers.google.com/web/updates/2016/08/removing-document-write
> 
> Has how to respond to this been discussed yet?

Not yet, but thanks for bringing this to our attention. 

Here are the interesting bits from the linked doc

> With this data in mind, the Chrome team have recently announced an intention to intervene on behalf of all users when we detect this known-bad pattern by changing how document.write() is handled in Chrome (See Chrome Status). Specifically Chrome will not execute the <script> elements injected via document.write() when all of the following conditions are met:
> 1. The user is on a slow connection, specifically when the user is on 2G. (In the future, the change might be extended to other users on slow connections, such as slow 3G or slow WiFi.)
> 2. The document.write() is in a top level document. The intervention does not apply to document.written scripts within iframes as they don’t block the rendering of the main page.
> 3. The script in the document.write() is parser-blocking. Scripts with the ‘async’ or ‘defer’ attributes will still execute.
> 4. The script is not already in the browser HTTP cache. Scripts in the cache will not incur a network delay and will still execute.
> 5. The request for the page is not a reload. Chrome will not intervene if the user triggered a reload and will execute the page as normal.

Rewriting the fallback looks like a mighty fine pull request subject for some lucky githubber.

**Comment by jpdevries** [comment]
Thank you for opening the issue @roblarsen. I've been wondering if maybe adding `defer` to all included scripts would solve this?

> Scripts with the ‘async’ or ‘defer’ attributes will still execute.

Something like

```html
<script defer src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
<script defer>window.jQuery || document.write('<script defer src="js/vendor/jquery-1.12.4.min.js"><\/script>')</script>
<script defer src="js/plugins.js"></script>
<script defer src="js/main.js"></script>
```

The 
```html
<script defer>window.jQuery || document.write('<script defer src="js/vendor/jquery-1.12.4.min.js"><\/script>')</script>
```
is like some sort of `defer` inception. Seems to work, but not sure if that is correct.

**Comment by roblarsen** [comment]
@jpdevries I think rewriting the include script to use a modern DOM interface (parentNode.insertBefore) like Google Analytics uses would be something to look at as well.

**Comment by FagnerMartinsBrack** [comment]
Related discussions about this that can help drive the decision:

* [/r/programming](https://www.reddit.com/r/programming/comments/52dnb4/chrome_is_intervening_against_documentwrite/)
* [/r/javascript](https://www.reddit.com/r/javascript/comments/52dn1k/chrome_is_intervening_against_documentwrite/)
* [/r/webdev](https://www.reddit.com/r/webdev/comments/52dn3x/chrome_is_intervening_against_documentwrite/)

**Comment by roblarsen** [comment]
@FagnerMartinsBrack Thanks for the links. Your own thread on reddit helped clarify things. As long as there's a cross-origin condition we don't have anything to worry about.

**Comment by hexalys** [comment]
A defer strategy is the best option in my opinion. I don't like async at all, for scripts that must be ready ASAP like jQuery.  I have suggested a  longer term implementation in the WICG/interventions thread...

@jpdevries Two things with your 'defer' code:

1. Defer on an inline `<script>`s has been deprecated by WHATWG. The poor insufficient reason given was that no one used it... True lame story, but it sadly happened.... So `defer` inception won't work. :(

2. 'defer' execution order has been buggy in IE 8-9. And there were issues with the 'interactive' event firing too early in IE 9-10 which could affect 'defer' scripts execution. The later can be circumvented; However that involves a hack and a bottom inline script to trigger 'interactive' correctly... So the condition for a public boilerplate using `defer` is mainly waiting for IE10 usage to die.

**Comment by jpdevries** [comment]
@hexalys 😭 I've been using defer inception for things like h5bp style CDNs with local fallback or doing feature detection before including something like a polyfill. That is a bummer!

**Comment by roblarsen** [comment]
Closing! We're safe!

**Comment by jpdevries** [comment]
@roblarsen oh that is great! Did Chrome revert their decision? I'm curious why we're safe because I really ❤️ this pattern

**Comment by roblarsen** [comment]
@jpdevries It's only triggered when the request is cross-origin so we're fine. It's a local fallback after-all.
