### ISSUE TITLE
Release New Major Version (6.0)

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#1897]
We've dropped IE8 support, which means a bold new era! Also, it's been a while! **Let's put on a show!** Or at least release some code. 

![mickey-rooney](https://cloud.githubusercontent.com/assets/361421/18998206/9ce32234-8705-11e6-8fb3-7bb398b2593f.jpg)

I started adding issues to the 6.0 milestone. Please share your anecdotes, comments and concerns.

**Comment by t1st3** [comment]
Yeah, at some point, I was thinking that removing crossdomain.xml (as we did in #1881) was a breaking change and needed a major bump. Glad to see it's coming!

**Comment by roblarsen** [comment]
![download](https://user-images.githubusercontent.com/361421/28085551-0f4b53e0-664a-11e7-8f8d-9fca928e2e6d.jpg)

**Comment by roblarsen** [comment]
I'm going to update the JS docs page and then... I'm shipping this thing? Something like that. WTHELL

**Comment by roblarsen** [comment]
This part is buttoned up. Just need to update the site.

**Comment by roblarsen** [comment]
[it is done](https://github.com/h5bp/html5-boilerplate/tree/6.0.0)
