### ISSUE TITLE
//html5shiv.googlecode.com/svn/trunk/html5.js

### ISSUE THREAD

**Issue by jevho** [h5bp/html5-boilerplate#1898]
It tries to get the shiv from the google CDN by this link which leads to 404.

**Comment by sanspace** [comment]
Which file are you referring to?

**Comment by jevho** [comment]
When you create a classic custom build with 'HTML5shiv' option chosen, in header of 'index.html' file you get the following code:
`        `
And '//html5shiv.googlecode.com/svn/trunk/html5.js' link leads to 404.

**Comment by roblarsen** [comment]
@jevho wrong repo https://github.com/verekia/initializr

**Comment by roblarsen** [comment]
I created a [pull request](https://github.com/verekia/initializr/compare/master...roblarsen:patch-1) to fix the issue over there.

**Comment by sanspace** [comment]
Thank you, @roblarsen! I was clueless about the original post. :sweat_smile:

**Comment by roblarsen** [comment]
Happy to help. I love easy pull requests.

**Comment by jevho** [comment]
Thanks to everyone!
My first post on github :)

**Comment by n1x1** [comment]
I'm sorry but am not sure if I get it...do I need only this link in my head element?
 '//html5shiv.googlecode.com/svn/trunk/html5.js'

or do I need all of this with the link above?

**Comment by coliff** [comment]
@n1x1  That link is old... Use this instead:
```
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
```

**Comment by n1x1** [comment]
@coliff Thanks, how can I stay up to date with scripts like this one? ...I'm still learning and don't know all the right staff and places to be up to date.
And just to be sure once more, I copy this script in the header of my index.html file?

**Comment by coliff** [comment]
Yes, copy and paste that snippet above in the header of all of your pages - then you can forget about it. That script isn't very likely to be updated to a newer version. It just makes things a bit better for IE 8. Bootstrap have a good starter HTML template you may be interested in: https://getbootstrap.com/docs/3.3/getting-started/#template

**Comment by n1x1** [comment]
@coliff ok, thank you very much, big help.

**Comment by choicegroup** [comment]
https://choicegroup.github.io/business/
Don't work slider of this website. Please solve this problem any body.

**Comment by WhiteITHack** [comment]
Эту ссылку  использовать прям в комментарии? И она будет работать?

**Comment by coliff** [comment]
> Эту ссылку использовать прям в комментарии? И она будет работать?

Yes, use it in a comment as above and it'll work for IE8... or even shorten the snippet to this:

```
<!--[if IE]><script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script><![endif]-->
```

**Comment by WhiteITHack** [comment]
Спс

**Comment by z10r** [comment]
It works, but I am hosted with Github Pages/Jekyll and I can not edit this. How can I fix this?
