### ISSUE TITLE
Add ARIA Attributes

### ISSUE THREAD

**Issue by shenoa** [h5bp/html5-boilerplate#1912]
I noticed that accessibility is currently addressed in the [Miscellaneous](https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/extend.md#miscellaneous) section of the Extend.md page in documentation. I think a JS dependency is good to add to existing projects, but perhaps not the best idea for a boilerplate. 

I would suggest that more accessibility elements, such as roles, be incorporated into the boilerplate. I'm just getting started in digging into ARIA, but screen reader compatibility is something I'd like to see more widely attended to. If this is something folks would like to see, I'd be happy to work on it with others.

**Comment by AlexxNica** [comment]
+1 for Accessibility;

Regarding JavaScript, I don't think it's a good idea to let go of it, as h5bp's repo description says:
"A professional front-end template for building fast, robust, and adaptable web apps or sites."

If you want a professional front-end template with all those features, you're going to need JavaScript.

**Comment by roblarsen** [comment]
Closing, with a pointer to some project history on this front:
#5
#204
#398
#1033
#1491

Default markup (along with aria roles) was removed in 5469e27 with discussion in #203.
