### ISSUE TITLE
Doesn't redirect to non-www when forcing https enable

### ISSUE THREAD

**Issue by jefrydco** [h5bp/html5-boilerplate#1922]
non-www redirection is working well by default. But when i try to enable force https, the non-www redirection doesn't work.
![redirection](https://cloud.githubusercontent.com/assets/20434351/24040837/73266d04-0b3d-11e7-8b69-52e1dde9a423.png)

**Comment by roblarsen** [comment]
I'm not sure what this is. It's not an issue with this repo.
