### ISSUE TITLE
Blocking all .files in .htaccess causes Let's Encrypt install to fail

### ISSUE THREAD

**Issue by adamjansch** [h5bp/html5-boilerplate#1933]
I just tried to install Let's Encrypt through my webhost's cPanel but ran into a problem where the install failed because a file generated by the process was blocked by HTML5 Boilerplate's .htaccess file.

The LE auto-install process sets a file in /.well-known/acme-challenge, and in trying to access that file a 403 error is generated. When I commented out the `RewriteRule (^\.|/\.) - [F]` rule and re-ran the install succeeded. (I don't yet know if this will be a problem for renewing certificates.)

Can this filepath be whitelisted?

**Comment by roblarsen** [comment]
We just consume the .htaccess file, here, issues [live in another repo.](https://github.com/h5bp/server-configs-apache)
