### ISSUE TITLE
Wrong version of jquery in the downloadable version of H5BP

### ISSUE THREAD

**Issue by oliverfunk** [h5bp/html5-boilerplate#1938]
jquery v1.12 is included and not the most recent version.
It's strange because v3.2.0 is in the dist/js/vendor folder of the main branch.

This is a freshly downloaded from the H5BP site:
[html5-boilerplate_v5.3.0.zip](https://github.com/h5bp/html5-boilerplate/files/923800/html5-boilerplate_v5.3.0.zip)

**Comment by roblarsen** [comment]
We haven't cut a proper release in a long while, so 5.3 is the latest release. I'm trying to get a new major release out the door soon. It's actually getting pretty close but I can only work on it in fits and starts.
