### ISSUE TITLE
Is JS "jQuery / modernizer" necessary for the h5b template?

### ISSUE THREAD

**Issue by stebdjui** [h5bp/html5-boilerplate#1944]
Hello,

i want create templates with less javascript as possible.
So i have a fundamental question:

**Are jQuery & modernizr necessary for running a html5-boilerplate template?**
I cant find any hints about that.

And secondly: Need the ga snippet any of these js files?

And yes, i know the benefits of modernizr and how it works.

**Comment by roblarsen** [comment]
The only requirement is what your saite requires so you can do whatever you want with the code
