### ISSUE TITLE
why html5boilerplate is stuck to V5.3.0 with old version of all Bootstrap, normalize & modernizr?

### ISSUE THREAD

**Issue by archimj03** [h5bp/html5-boilerplate#1945]
I just noticed that when I download html5boilerplate V5.3.0 it comes with

Bootstrap v3.3.1 (but Bootstrap v3.3.7 is available)
normalize.css v3.0.2 (but normalize.css 7.0.0 is available)
modernizr 2.8.3 respond 1.4.2 (but modernizr 3.5 is available)
so why html5boilerplate come with old version of Bootstrap, normalize & modernizr ? Can I update latest version of all Bootstrap, normalize & modernizr on my own ? will that break any settings of html5boilerplate ? is it safe to update all Bootstrap, normalize & modernizr on my own ?

Again how can I update Bootstrap, normalize & modernizr into html5boilerplate ? any shortcut or something ?

Usefull links : 1. https://html5boilerplate.com/ 2. https://necolas.github.io/normalize.css/ 3. http://getbootstrap.com/ 4. https://modernizr.com/

**Comment by stebdjui** [comment]
+1

**Comment by roblarsen** [comment]
1. You can grab the latest from Github which has updated version of just about everything (Except Modernizr which is one merged PR away, see: #1939) 
2. We're trying to release 6.0, but it's been a bit of a struggle for me to get the code out the door as I haven't had any long, solid blocks of time to work on it.  See: #1880

**Comment by archimj03** [comment]
@roblarsen thanks for quick response sir. again as you have suggested I have downloaded H5BP from GitHub. but I'm very new to GitHub so I'm getting confused. inside download from GitHub I have folder named "dist". according to my guess that is the only folder I need right? should I use "dist" folder ? and delete all the other files and folders outside of that "dist" ? 

question 2. is I have checked that "dist" folder also. inside of that also. version of normalize.css is 5.0.0 n latest version is 7.0.0. so should I download normalize.css from official website and replace that normalize.css file inside of "dist/css" folder? would that break anything? any setup of H5BP will be Disturbed? or clash? should I wait for you to update normalize.css version inside of H5BP coz you need to integrate something for updating normalize.css? 

question 3. which is a last stable version of H5BP ? one which I can download from H5BP official website ? or one which is from GitHub with new version of all normalize.css and etc ?

**Comment by roblarsen** [comment]
Yes, `dist` is all you need. You can also copy it to whatever location you need.

2. Nothing would break.  HTML5 Boilerplate is a starting point so people can and will do all sorts of things on top of the base code. You don't need to wait for anything. The code is for you to manipulate as you will.

3. Realistically, HEAD (the latest in Github) is quite stable. The changes we make end up taking some time usually so they're good and ready once they make it into the main branch. That said, the last release remains 5.3.

**Comment by archimj03** [comment]
tx for updating modernizr everything is updated only normalize.css 7.0.0 is left to update then H5BP is ready to latest version of all sir plz if u can

**Comment by klonos** [comment]
@archimj03 there are good reasons why a lot of projects have not updated their normalize.css: https://github.com/necolas/normalize.css/issues/664

...there were breaking changes from v5 to v6 ...which were then reverted.
