### ISSUE TITLE
Publish to NPM?

### ISSUE THREAD

**Issue by alexandernst** [h5bp/html5-boilerplate#1946]
I see this has been pushed to NPM ( https://www.npmjs.com/package/html5-boilerplate ), but it's outdated. Can you update it?

**Comment by roblarsen** [comment]
this is the first I've heard of an NPM  package, so we'll have to figure out what's going on with that before anything else can happen

**Comment by alexandernst** [comment]
So maybe don't close the issue before actually figuring out what's going on and publishing to NPM?

**Comment by roblarsen** [comment]
I'm going to create another, broader. issue.

**Comment by TigersWay** [comment]
You're going to find much more than 1....

**Comment by roblarsen** [comment]
@TigersWay Oh, I bet. That one matches the github project name, so I'm just going to worry about that one since that's what people will guess at.
