### ISSUE TITLE
Publish official NPM package

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#1947]
This just in, from the _I don't have time for this department_:

As was just pointed out (#1946 thanks @alexandernst for opening the issue.) there's an [unofficial npm package](https://www.npmjs.com/package/html5-boilerplate) out there. We should totally publish a real one (and document it- it's super weird that the readme on npm doesn't mention installing it with npm.)

I'm working on getting the package name and will create an h5bp organization (if someone isn't sitting on  _that_ too) to control the package, but if someone else wanted to create a PR to work through the plumbing, I would shower you with praise.

**Comment by jpdevries** [comment]
I'd be willing to contribute, but not sure where to start. I looked at the npm package and it doesn't seem to offer much other than "hey you should download h5bp and use it". My question is what would the goals be for h5bp to publish an official package. What sort of things, if any, would change given that they are creating a site and using npm modules, rather than just creating a static site.

**Comment by roblarsen** [comment]
@jpdevries It's all open for discussion. I don't think it makes a ton of sense to publish it to npm in the first place (you're going to have to do manual labor to use the project anyway), but I'd rather have the package be under our control and make as much sense as possible (just publishing the ./dist/ folder, for example) if it is going to be out there.

**Comment by jpdevries** [comment]
@roblarsen got it. if they squat the package join 'em!

**Comment by roblarsen** [comment]
I have control of the package. Now, I just need to find time to do something with it.

**Comment by simonferry** [comment]
But why? Whu should you publish that?

**Comment by folknor** [comment]
Because someone else already did, and there's 100 downloads per day, which means that some people are using it for whatever reason.

**Comment by roblarsen** [comment]
[I started setting this up](https://github.com/h5bp/html5-boilerplate/blob/npm/package.json)

**Comment by roblarsen** [comment]
closed via #1988
