### ISSUE TITLE
JQuery version 1.12.0.min.js

### ISSUE THREAD

**Issue by BellemareMederic** [h5bp/html5-boilerplate#1954]
**I'm submitting a ...**

- [x] bug report

On your website the version of jquery is the old one. need update

**Comment by coliff** [comment]
Hi there - HTML5 Boilerplate will release a major new version soon (v6) and the version of jQuery will be updated then (to v3.2.1) as support for Internet Explorer 8 will be dropped.

**Comment by roblarsen** [comment]
As above!
