### ISSUE TITLE
Best practices for iPhone X

### ISSUE THREAD

**Issue by Math3v** [h5bp/html5-boilerplate#1995]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

With the announcement of iPhone X, Apple has released a new guideline for web developers. In order to provide the best user experience on the new iPhone X, we should consider this [guideline](https://webkit.org/blog/7929/designing-websites-for-iphone-x/).

**Comment by roblarsen** [comment]
Easy, no tech PR here!

**Comment by reef289** [comment]
When doing mobile optimization start with mobile and work your way up. Apple has developer guides on their website as well.

**Comment by coliff** [comment]
As all new iPhones have this form factor it's becoming increasingly important to add some details about this to H5BP. I suggest we mention it in the mobile-viewport section of the html docs (https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/html.md#mobile-viewport). I'll make a PR for this

**Comment by coliff** [comment]
This is in the docs as of v7.0

https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/html.md#mobile-viewport
