### ISSUE TITLE
Gulp build uses node-sri which uses cat and fails in Powershell/cmd.exe

### ISSUE THREAD

**Issue by Vincent2015** [h5bp/html5-boilerplate#1997]
**Error: Command failed: cat node_modules/jquery/dist/jquery.min.js | openssl dgst -sha256 -b.......**

**Comment by roblarsen** [comment]
@Vincent2015  "When rerun?" 

Meaning you can build the project once?

does "node_modules/jquery/dist/jquery.min.js" exist?

**Comment by paulrobello** [comment]
I am running on a Win64 OS and the command output below is clearly trying to run linux related commands such as cat.

(node:17044) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Error: Command failed: cat node_modules/jquery/dist/jquery.min.js | openssl dgst -sha256 -binary | openssl enc -base64 -A
'cat' is not recognized as an internal or external command,
operable program or batch file.

**Comment by roblarsen** [comment]
@paulrobello thanks! I get it now. The "rerun" distracted me from  `cat.` The real issue is just running the build under powershell/cmd.exe.  

If you need to build the project right now, use [git bash, which comes with git for windows](https://git-for-windows.github.io/) 

I know that works as it's what I use on Windows to manage the project. 

I'll rename the issue to better reflect the bug.

**Comment by roblarsen** [comment]
[The culprit](https://github.com/odino/node-sri/blob/master/index.js#L23)

**Comment by roblarsen** [comment]
If someone wanted to rewrite that task to use something else (maybe [ssri](https://github.com/zkat/ssri)) then I would be very happy and I would merge that pull request.

**Comment by Vista1nik** [comment]
Try to build this project in bash.

If you on Windows 10 you can use
**Ubuntu** from Windows Store!
or use `https://git-scm.com`

**Comment by roblarsen** [comment]
Thanks @Vista1nik for the pointer to Ubuntu in the Windows Store. That's a new alternative for folks. 

I'd still like to fix the underlying issue so that the build is just node and we won't have to worry about it at all.
