### ISSUE TITLE
Is there a mistake in the sentence?

### ISSUE THREAD

**Issue by byog** [h5bp/html5-boilerplate#2002]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))

The sentence “Include the following meta tag will unintrusively allow the **user the option** to download your iOS app” in extend.md lets me confused.I think should "allow the user use the option".

**Comment by coliff** [comment]
I think you're right that the current sentence doesn't quite make sense.
"allow the user use the option" doesn't make sense either though. I'd suggest:

> Including the following meta tag will unintrusively give the user the option to download your iOS app

**Comment by byog** [comment]
I think so.

**Comment by byog** [comment]
I need to open a PR for this?

**Comment by roblarsen** [comment]
@byog if you would like the change to be added to the project.

**Comment by byog** [comment]
Ok, I will do.
