### ISSUE TITLE
Remove travis-after-all (deprecated)

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2020]
The Gulp file currently has 'travis-after-all' though this project has been deprecated (https://github.com/alrra/travis-after-all).
The functionality it provided is now supported natively by Travis CI via Build Stages (https://blog.travis-ci.com/2017-05-11-introducing-build-stages).

I'm not too familiar with Travis so opening this as an issue if someone else wants to open a PR

**Comment by reddysridhar53** [comment]
Is this still open?

**Comment by roblarsen** [comment]
@reddysridhar53 It is
