### ISSUE TITLE
Atom Feed url in documentation

### ISSUE THREAD

**Issue by stardisblue** [h5bp/html5-boilerplate#2023]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))
- [x] documenation

The atom feed link point to an expired domain with a tons of advertisement redirections.
https://github.com/h5bp/html5-boilerplate/blob/master/dist/doc/extend.md#atom
http://www.atomenabled.org/developers/syndication/ <- proof

**Comment by coliff** [comment]
Thanks for reporting this @stardisblue  - I opened a PR to fix it (updated link to point to Wikipedia article on Atom Feed)
