### ISSUE TITLE
Separate file for the print stylesheet

### ISSUE THREAD

**Issue by bueltge** [h5bp/html5-boilerplate#2046]
**I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] other

## Feature requests
Really often the print stylesheet is forgotten or insufficiently. I think the h5bp project have the visibility and chance to makes the topic more visible. However the project should use a separate file and also a separate link tag for the print stylesheet. I think this makes it more visible in the `index.php` and more visible for the creation of the stylesheet.

```html
  <link rel="stylesheet" href="css/normalize.css">
  <link rel="stylesheet" href="css/main.css">
  <link media="print" rel="stylesheet" href="css/print.css">
</head>
```

We should discuss to use the media attribute with value `screen` for normalize and the main.css so that is not necessary to overwrite, redefine the values in the print stylesheet.

Also it has the chance that we get a solid `print.css` for a lot of use cases, easier to maintain and more focus on important topic for the media `screen` in the `main.css`.

I would send a pull request if other se it also and like the idea. However maybe I'm wrong with my view to this topic. Thanks for your time and feedback.

**Comment by roblarsen** [comment]
I think an interesting way to highlight this will be to move the CSS files into a separate project, as we've previously discussed.

**Comment by coliff** [comment]
I don't think it's a good idea to include a print-only stylesheet in the head of the project - it creates an extra file to manage, it creates an extra HTTP request which will impact performance.

It's good that we include CSS for improved printing, but it doesn't need to be a different CSS file in production. If anything it should be a seperate CSS file which gets combined at build time - just like Bootstrap does for example:
https://github.com/twbs/bootstrap/blob/v4-dev/scss/_print.scss

**Comment by bueltge** [comment]
The discussion is helpful. The request it is a real topic and in a production site I would prefer to use only one css. However for the normalize we use also a request, a separate file. But also here the result should use one request for the stylesheet.
But this separation will help to focus on the goal to create always a print style and get a maintained print stylesheet.

@roblarsen now the issue is closed, how should this help to get a solid discussion and visibility for this topic?

**Comment by roblarsen** [comment]
Thanks to this issue I was reminded that I liked the idea of separating out [main.css](https://github.com/h5bp/main.css) into its own repo, so we'll be able to discuss the development of the print section of main.css there and since we'll also use SCSS to generate it, we could automate the production of a separate print.css as well. If that project is able to build individual components, there's no reason we can't offer a build that looks like what you want.
