### ISSUE TITLE
Border problem

### ISSUE THREAD

**Issue by MooijGedaan** [h5bp/html5-boilerplate#2054]
Hi there,

I've got a problem with the border. If a text is to long, it just goes out of it's border. When I disable and enable the border in the code in Safari it shows as it should be. Is there a way to fix this?

How it should be
<img width="384" alt="schermafbeelding 2018-05-26 om 23 21 37" src="https://user-images.githubusercontent.com/39658340/40580276-993b4794-613b-11e8-9013-66170b95dad8.png">

How it is
<img width="381" alt="schermafbeelding 2018-05-26 om 23 21 46" src="https://user-images.githubusercontent.com/39658340/40580277-995288a0-613b-11e8-8b56-771941de644a.png">

**Comment by roblarsen** [comment]
Hi, I'm not sure what this has to do with HTML5 Boilerplate
