### ISSUE TITLE
Leave web.manifest `display` at default setting

### ISSUE THREAD

**Issue by philwareham** [h5bp/html5-boilerplate#2090]
In the web.manifest, stating `standalone` is too opinionated, see https://developer.mozilla.org/en-US/docs/Web/Manifest#display

> In this mode, the user agent will exclude UI elements for controlling navigation, but can include other UI elements such as a status bar.

Since html5-boilerplate is can be used for both apps _and_ websites, changing the default `display` state (`browser`) to `standalone` opines that this is specifically a web app, removing UI beneficial to a website.

TLDR; omit `display` rule and leave it to default state `browser`. If a user wants to add `"display": "standalone"` themselves then they can

**Comment by roblarsen** [comment]
@coliff we re-added this property based on your testing? I believe we need a default, so should it be display:browser? That would be same as omitting it which broke something, somewhere?

**Comment by coliff** [comment]
We added `"display": "standalone"`to the manifest in PR #2060.

Not having `display:` defined in the manifest gives an error in Google Lighthouse's 'Progressive Web App' test, but really, it's not a problem at all if you're adding a manifest for improving the 'add site bookmark to homescreen' experience (manifests aren't purely intended for PWAs).

So I agree with @philwareham - we should remove it and I'll open a new PR for that now.

**Comment by roblarsen** [comment]
👍

**Comment by coliff** [comment]
Opened a PR in #2096. I was wondering if we needed to update the docs, but I took a look at what we have currently:

> Our [site.webmanifest](https://github.com/h5bp/html5-boilerplate/blob/master/src/site.webmanifest) contains a very skeletal "app" definition, just to show the basic usage. 
You should fill this file out with [more information about your site or application](https://developer.mozilla.org/en-US/docs/Web/Manifest)

So I think we're good. It has a link to Mozilla's excellent docs for further info.
