### ISSUE TITLE
[Manifest] Consider ChromeLabs PWACompat

### ISSUE THREAD

**Issue by Malvoz** [h5bp/html5-boilerplate#2101]
I suggest H5BP to consider https://github.com/GoogleChromeLabs/pwacompat
Thoughts?

**Comment by coliff** [comment]
I personally don't think we should add or recommend that for the reasons outlined here:
https://medium.com/@firt/you-shouldnt-use-chrome-s-pwacompat-library-in-your-progressive-web-apps-6b3496faab62

**Comment by Richienb** [comment]
A `site.webmanifest` file is required to be present in order for this to work. The problem with H5DP is that it is essentially **optional** to include such file. Nonetheless, there aren't enough icon files specified in it anyways.
