### ISSUE TITLE
Possible to remove shrink-to-fit=no ?

### ISSUE THREAD

**Issue by scottaohara** [h5bp/html5-boilerplate#2102]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

## Feature (removal) requests
Throwing out the idea to remove the `shrink-to-fit=no` portion of the view port meta tag.

Per my findings, the need for it as a default was rectified with the release of iOS 9.3, where the viewport no longer shrunk to accommodate overflow, as was introduced in iOS 9.

[Test finds reported on my blog post](https://www.scottohara.me/blog/2018/12/11/shrink-to-fit.html) 

Per the readme for html5 boilerplate indicating support for the last 2 versions of Safari, this would indicate that it'd be safe to drop.

The counter argument to this issue is that it hurts nothing by leaving it there.

Thank you :)

**Comment by roblarsen** [comment]
👍 

Want to PR?

**Comment by scottaohara** [comment]
Will do.

**Comment by htho** [comment]
Hi  dear html5-boilerplate community and @scottaohara (I found no other way to get in touch with you),

I spend almost a week trying to figure out why our website behaves so strangely on iPads.
At one point I stumbled upon the `shrink-to-fit=no` viewport meta tag.
And all the sudden things worked as expected, and as in other browsers/devices.

I read your article and wondered I apple changed behavior again.
These are screenshots taken on an iPad (10. Generation, simulator) running iOS 17.2:

![Simulator Screenshot - iPad (10th generation) - 2024-03-27 at 14 52 06](https://github.com/h5bp/html5-boilerplate/assets/2182288/17950984-a76d-4442-9538-611ab88be62a)

![Simulator Screenshot - iPad (10th generation) - 2024-03-27 at 14 52 38](https://github.com/h5bp/html5-boilerplate/assets/2182288/34fcd780-de7d-4d64-8b2e-38c3096b6a87)

As you can see, the screenshots look quite differently.
I don't know what they looked like in 2015 when the tag was introduced, or in 2018 when @scottaohara  wrote [his article](https://www.scottohara.me/blog/2018/12/11/shrink-to-fit.html), but I fear the case for `shrink-to-fit=no` is back.

What do you think, do we need to bring back `shrink-to-fit=no` to html5boilerplate?
Or did I get something wrong?

**Comment by scottaohara** [comment]
seems to work properly on my iphone, but yes, appears there is a potential regression when testing on an ipad.

imo, this seems like an issue to file against apple and have them fix the issue, rather than depend on a boilerplate to re-include a meta tag to fix the symptom, rather than the actual problem.

additionally, from my brief testing, this only seems to be causing a problem if a website has some quirks in their media queries / has elements that extend beyond the viewport.  i'm not seeing an issue for websites that don't have bi-directional scrolling issues caused by elements that can't fit inside the ipad's viewport.

but, y'all do what y'all want to do here i guess.

**Comment by htho** [comment]
Hey Scott, I also found that it works on an iPhone.
You are right, it's probably not necessary for most websites.
At this point my research is done, I am fine with including the meta tag.

**Comment by scottaohara** [comment]
would still be awesome if you opened a bug against apple though :D

**Comment by htho** [comment]
> would still be awesome if you opened a bug against apple though :D

Done: https://bugs.webkit.org/show_bug.cgi?id=271819
