### ISSUE TITLE
The link to the documentation gives a 404

### ISSUE THREAD

**Issue by enriquemorenotent** [h5bp/html5-boilerplate#2123]
If you go to https://html5boilerplate.com/ and press DOCS in the main menu, you land in a 404 page

**Comment by roblarsen** [comment]
Thanks. I'll take a look.

**Comment by roblarsen** [comment]
closed via [bea2ab](https://github.com/h5bp/html5boilerplate.com/commit/bea2abf82fa0babd1a0a5293b3a8a0909a74ca7e)

**Comment by enriquemorenotent** [comment]
Great, thanks
