### ISSUE TITLE
Add Social Media Preview Image

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2127]
reference: [Customizing your repository's social media preview](https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview)

**Comment by coliff** [comment]
I think we'd be fine with specifying an Opengraph Image on the page instead (we should really have done this already) so GitHub uses that. We can set the hi-res icon as the artwork. This means no need to edit settings or create new artwork and if it's shared on Facebook the preview will look nice there too.

Opengraph Preview:
https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fhtml5boilerplate.com
