### ISSUE TITLE
Question: any reason why package-lock.json is still ignored

### ISSUE THREAD

**Issue by fendorio** [h5bp/html5-boilerplate#2146]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [X ] other (Please do not submit support requests here (below))

Just submitted a PR which removed package-lock.json from the .gitignore file, I see this was added to .gitignore back in 2017, when there was an issue with npm r.e. the package-lock.json file. This issue has since been solved. Hold my hands up, I didn't read contributing, so blow it away by all means, it is of course a simple 1 line deletion.

With package-lock.json in .gitignore, using npm is essentially blocked, unless you either remove it from the .gitignore file, or use yarn. 

Hence my question, since the original issue with the package-lock.json file is now resolved, in my opinion this should be removed from the .gitignore file, allowing package-lock.json to be checked back into source control.

**Comment by roblarsen** [comment]
You could pore over our history and see that we did in fact do as you guessed, block it because it was kind of a mess initially. It has fallen through the cracks since. I'll merge your PR.

**Comment by roblarsen** [comment]
closed via #2145 👍

**Comment by fendorio** [comment]
Nice one, yes I did go over the old issues & PR's and could see what happened, and why :) Think I commented on this in the PR, anyway nice one for this, cheers :)
