### ISSUE TITLE
Consider adding scss alternatives for existing css files?

### ISSUE THREAD

**Issue by kapantzak** [h5bp/html5-boilerplate#2148]
I didn't find any older post asking for something similar and I wonder if it whould be a nice feature for the project to contain some **.scss** files for anyone might want to use css preprocessor, for example:

    /dist
        /css
            main.css
            normalize.css
            main.scss
            normalize.scss

I could make a PR if the team thinks this is a good idea.
Thanks

**Comment by roblarsen** [comment]
Both of those files only exist in the project at build time so any variation would have to happen upstream. 

main.css is managed in a separate project:

 [h5bp/main\.css: A repository for the development of the HTML5 Boilerplate CSS file, main\.css](https://github.com/h5bp/main.css) We can talk about what that might look like over there. 

normalize.css is managed in a separate project by a former maintainer of this project.  I'm pretty sure someone has suggested something like that to him at some point. 

[necolas/normalize\.css: A modern alternative to CSS resets](https://github.com/necolas/normalize.css/)
