### ISSUE TITLE
Unable to build or test project

### ISSUE THREAD

**Issue by kapantzak** [h5bp/html5-boilerplate#2149]
I am unable to run tests or build the project on cloned repo (**version 7.2.0**):

## Steps to reproduce

    npm install
    npm run test

![test](https://user-images.githubusercontent.com/12742884/63939234-6a976c80-ca6f-11e9-8378-8fc843942da5.png)

Same error when

    npm run build

![build](https://user-images.githubusercontent.com/12742884/63939238-6e2af380-ca6f-11e9-8842-eacbeb5d41ef.png)

## Environment

- Windows 10
- node 10.16.0
- npm 6.9.0

**Comment by roblarsen** [comment]
Looking now. thanks for the report

**Comment by roblarsen** [comment]
Verified. Tests run and pass with node v9.11.2

With 10.16.3 it fails.

![image](https://user-images.githubusercontent.com/361421/63944873-630c9f00-ca40-11e9-8677-31b8182fa045.png)

**Comment by roblarsen** [comment]
Based on my research, this looks like a job for the gulp 4 upgrade that I've been putting off because I have zero interest in doing that particular task. I'll open an issue and maybe tweet out a help wanted.

**Comment by roblarsen** [comment]
closed via #2151
