### ISSUE TITLE
Repository Corruption: git ops fails in strict fsck mode

### ISSUE THREAD

**Issue by Nirmal4G** [h5bp/html5-boilerplate#2160]
**I'm submitting a Repo corruption report**

Unlike GitHub, GitLab has stricter fsck requirements and so does my Git installation. When I tried to clone this repo, I got the `zeroPaddedFilemode` errors. Eventually I changed my `.gitconfig` to ignore the errors but when I pushed to GitLab, it rejected my push because of these errors. Unfortunately, I can't change GitLab's config of my repo forked from this.

## Repro

```
$ git fsck --full --strict
Checking object directories: 100% (256/256), done.
error in tree 0d0c9b8a4231b330d6c30551d2bd24e7d4be3ec9: zeroPaddedFilemode: contains zero-padded file modes
error in tree 262d2482031f841952dfb80069087c9e9dd5b228: zeroPaddedFilemode: contains zero-padded file modes
error in tree 995a1bae68bf81dc15fae330733de79c59d2a506: zeroPaddedFilemode: contains zero-padded file modes
error in tree b61366f153ac510b70159604baf27ce80c7afde0: zeroPaddedFilemode: contains zero-padded file modes
Checking objects: 100% (7412/7412), done.
```

## Solution

The only known fix is to rebuild the repo using Git's `fast-export` and `fast-import` commands.

```sh
git fast-export --all | (cd ../empty-repo/ && git fast-import)
```

Here's the [`zeroPaddedFilemode`](https://stackoverflow.com/q/14700502/1526863) Q/A on StackOverflow for further reference.

**Note:** _I know that we probably won't rebuild the repo since the SHAs change but I'm putting the issue here for the future reference._

**Comment by roblarsen** [comment]
thanks for the report
