### ISSUE TITLE
html5-boilerplate_v7.3.0.zip is not HTML5 Boilerplate v7.3.0

### ISSUE THREAD

**Issue by stordoff** [h5bp/html5-boilerplate#2180]
**I'm submitting a ...**

- [X] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (below))

Basically, as title - html5-boilerplate_v7.3.0.zip from the GitHub releases page does _not_ contain HTML5 Boilerplate v7.3.0. Downloading the zip (https://github.com/h5bp/html5-boilerplate/archive/v7.3.0.zip) from the [tags](https://github.com/h5bp/html5-boilerplate/tags) page works fine.

Steps to reproduce:

1. Navigate to https://github.com/h5bp/html5-boilerplate/releases
2. Download html5-boilerplate_v7.3.0.zip (https://github.com/h5bp/html5-boilerplate/releases/download/v7.3.0/html5-boilerplate_v7.3.0.zip)
3. Inspect contents

Signs:

main.css opens with:

`/*! HTML5 Boilerplate v7.2.0 | MIT License | https://html5boilerplate.com/ */`

Shipped Modernizr is modernizr-3.7.1.min.js, contradicting:

> Updated to Modernizr 3.8

Oddly, some of the mentioned changes (such as #2155) do appear to have made it in, so I'm unclear what "version"/state this zip actually represents.

Edit: I've just diffed the two, and there are a few minor changes to .editorconfig. The releases page version includes:

```
[*.md]
trim_trailing_whitespace = false
```

And the documentation is missing a few updates (removing references Google+ and Bootstrap; updated links) as well.

**Comment by roblarsen** [comment]
The tagged version is just a snapshot of the repo at that point. I generate that download file manually and simply messed up the contents. I need to automate that to get operator error out of the way. 

I updated the zip file with the proper contents. Hopefully that will be reflected properly in the downloads going forward.

**Comment by stordoff** [comment]
Fair enough - I've just re-downloaded to double-check and all looks good now :)
