### ISSUE TITLE
500 Error using .htaccess

### ISSUE THREAD

**Issue by amityweb** [h5bp/html5-boilerplate#2187]
Been using boilerplate htaccess for some time, but thought I would update it. I receive a 500 error now. 

```
[Sat Jan 25 12:14:20 2020] [alert] [client 12.34.56.78.90] /home/mysite/public_html/.htaccess: error: envclause should be in the form env=envar
[Sat Jan 25 12:14:20 2020] [alert] [client 12.34.56.78.90] /home/mysite/public_html/.htaccess: error: envclause should be in the form env=envar, referer: https://www.mysite.co.uk/
```
Maybe older version of apache and backward compatibility is removed? I cant see any comments about it, to use an alternative, like I have to do with FollowSymLinks/SymLinksIfOwnerMatch

**Comment by roblarsen** [comment]
Hi @amityweb the server configs have their own repositories. So, in this case, [h5bp/server-configs-apache](https://github.com/h5bp/server-configs-apache) cc: @LeoColomb

**Comment by amityweb** [comment]
Ah right, ok thanks a lot. I've always just grabbed this one, but I haven't for a while hence updating it now.

**Comment by roblarsen** [comment]
We're happy to be the delivery mechanism for a lot of great work, but in many cases there are separate repos for the component parts.
