### ISSUE TITLE
AnonymizeIP for Google Analytics

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2212]
@coliff writes:

>by default Google Analytics records the full IP address of a user visiting the site, but that full IP address is never available to the Google Analytics property admin. By anonymizing the IP address you can make your site more GDPR-compliant as a full IP address can be defined as publicly identifiable information. There is almost no downsides to this, other than the location of users can be slightly less accurate at a city-level. We already provide info about AnonymizeIP in the docs but I think it might be worthwhile including by default. Worth a discussion....

**Comment by XhmikosR** [comment]
I personally do this in all my projects so I'm 💯
