### ISSUE TITLE
Celebrate 10 Years!

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2216]
[OMG we're going to be 10 years old](https://github.com/h5bp/html5-boilerplate/wiki/history#but-first)

We're working on a new release to coincide with this project turning ten years old, but beyond that I'd like to actually celebrate this thing a little bit and as part of that I'd love to get some thoughts/ anecdotes/praise/love letters to share when I write up the release. I'd obviously love to hear from the core folks past and present (👋 @paulirish @necolas @nimbupani @drublic @mathiasbynens @alrra ) but anyone else who's ever contributed or consumed the project is more than welcome to reach out. You can hit me up privately or just share your thoughts below.

**Comment by drublic** [comment]
Fantastic to see the template still being maintained after such a long time! Thanks for taking care @roblarsen and everyone else 💪

**Comment by amcintyre-cs** [comment]
I was there when the pink highlight first appeared. AMA.

**Comment by wall03** [comment]
> Fantastic to see the template still being maintained after such a long time! Thanks for taking care @roblarsen and everyone else muscle

Yup! So great :)

**Comment by niksy** [comment]
> I was there when the pink highlight first appeared. AMA.

`hotpink` is still my default debug color 😄

**Comment by SachithMayantha** [comment]
That's great

**Comment by KwameDaniel** [comment]
much more grace for template maintenance. Thanks for this

**Comment by insane-site** [comment]
I have been using this for quite some time and i love it thanks to all the past and present core developers.

**Comment by roblarsen** [comment]
Thanks everyone!
