### ISSUE TITLE
> Removing jQuery from the project has been suggested to me before, and was suggested as a discussion point for the upcoming 8.0 release by @coliff

### ISSUE THREAD

**Issue by thereaad** [h5bp/html5-boilerplate#2226]
> Removing jQuery from the project has been suggested to me before, and was suggested as a discussion point for the upcoming 8.0 release by @coliff
> 
> I'm open to discussing it. This ticket is the place for that discussion 🤔 😠 😄 😢
> 
> I'm not going to lay out my thoughts just yet, but I'll share what I think are the two different ways to look at it.
> 
> On the one hand- Builtwith's [jQuery Usage Statistics](https://trends.builtwith.com/javascript/jQuery) usage statistics indicate that it's in use on 76% of the top 1m sites. For many people it's still very much a thing.
> 
> On the other hand- For many people who active on GitHub and who stay on the cutting edge of front end development, jQuery is three or four generations old and doesn't have any place at all in their day-to-day development. It may live as a dependency somewhere in some projects, but doing a lot of `$()` stuff is something from the past.

_Originally posted by @thereaad in https://github.com/h5bp/html5-boilerplate/issues/2215#issuecomment-622323621_

**Comment by coliff** [comment]
hey there @thereaad  - did you mean to open this as a new issue? Can we close this to keep the original issue open for discussion?
