### ISSUE TITLE
Include bundler

### ISSUE THREAD

**Issue by vltansky** [h5bp/html5-boilerplate#2227]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below)

Not sure if necessary, so it's more like a question/discussion, but in my point of view if I would want to make some static HTML page using html5-boilerplate I would definitely use bundler for my JS and CSS (probably would go for SCSS).
So I would use webpack or parcel to be able to use modern javascript and etc. So it would be comfortable for me if html5-boilerplate includes default webpack configuration, so I'll be able right away just to `npm install` and `npm run build`.

What do you think? Or maybe I miss the point of the html5-boilerplate and its not relevant?

**Comment by roblarsen** [comment]
Many years ago, before there were JavaScript-based build tools of any stripe if you can imagine a time like that, we shipped with build tooling. We stripped that out to its own project in order to streamline the core offering. With the rise of Grunt/Gulp/WebPack that project was mothballed a few years ago. 

I'd be open to discussing something like this. I don't know what shape it would take but I'm open to it. I like the idea of something unobtrusive that could still be educational

**Comment by vltansky** [comment]
What if html5-boilerplate would contain `package.json` with dev dependencies and scripts.
If developer needs bundler he can just `npm install` and then will be able to use `npm run build` / `npm start`.
Config file can be a part of html5-boilerplate or generated in post/pre npm install hook.
Although `parcel` claims to be zero config bundler, so it could be a good option..

**Comment by vltansky** [comment]
Take a look on [example](https://github.com/vltansky/html5-boilerplate) with parcel.

**Comment by roblarsen** [comment]
This is interesting. I think the idea of a stub package.json is potentially a good one. There's a lot there that we could stub out to illustrate and document.  @coliff what do you think? None of this is very obtrusive, but I think it opens up some possibilities. I've got a little bit to get done with GitHub Actions before this release can go live so there's time to work on this and expand on it a little.  

🤔

**Comment by roblarsen** [comment]
Okay, I need to finish [shipping main.css v2.1.0](https://github.com/h5bp/main.css/issues/57) integrate that here and then I'm going to take a good look at this. The more I think about this the more I like it by itself (it's helpful, it should be unobtrusive and only adds one file to dist) and it opens up loads of possibilities (an entry in the package.json to add jQuery back in, for example.) 

I think it's going to push the release out  couple of weeks, but that's fine. I've still got the time.

**Comment by nioposiquit** [comment]
I am excited with this although I am newbie for using bundlers, I see the benefits it gives. I'm thinking of creating my own front-end template but not anymore after discovering this project.

**Comment by roblarsen** [comment]
close by #2229
