### ISSUE TITLE
Release 8.0 (home stretch)

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2248]
- [x]  Readme/changelog for create-html5-boilerplate (Anything else?)
- [x] Verify that create-html5-boilerplate publishes properly to npm with an RC
- [x]  Publish 0.1.0 of create-html5-boilerplate (github and npm)
- [x] Add npx documentation to the readme (✔️ #2251)
- [x] Docs update (#2251 although I'm eyeing the Extend doc) 
- [x] Changelog (WIP #2256)
- [x] Verify that the new package generation and release process works with an RC (Releases both npm and Github in one go)
- [x] Update the site
- [x] Actually do the release
- [x] Blog post
- [x] Tweet

(I'm missing something)

**Comment by SergioMazariego** [comment]
.

**Comment by roblarsen** [comment]
Publish works. I'm going to create a ticket to test and fine-tune the release.

**Comment by roblarsen** [comment]
We're ready to go. I'm going to let this sit for a few hours if anyone is interested in looking at the project again. The last commit should have everything synced up

**Comment by coliff** [comment]
The `package.json` in th `src/` dir has the keywords "h5bp",  "template", "front-end" - I wonder if we should remove those.... maybe remove keywords altogether as its not a required param.

**Comment by coliff** [comment]
also, I like this https://github.com/cameronhunter/prettier-package-json - it puts the param keys in a logical order. I think this is a bit better.

```
{
  "name": " ",
  "version": "0.0.1",
  "description": "",
  "license": "",
  "author": "",
  "scripts": {
    "build": "parcel build index.html",
    "dev": "parcel index.html --open",
    "start": "npm run build && npm run dev",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "parcel-bundler": "^1.12.4"
  }
}
```

**Comment by coliff** [comment]
great. I'll make a quick PR now

**Comment by roblarsen** [comment]
https://htmlcssjavascript.com/web/html5-boilerplate-8-0-0-released/
https://twitter.com/h5bp/status/1268919161389973505

**Comment by roblarsen** [comment]
🍾

**Comment by coliff** [comment]
🍻
