### ISSUE TITLE
Docs: Track page scroll in Google Analytics requires jQuery

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2252]
RE: https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/extend.md#track-page-scroll

This script requires jQuery. We should either update docs to mention that or remove this from the docs (now that jQuery isn't included)

**Comment by roblarsen** [comment]
Good eye

**Comment by roblarsen** [comment]
I'll just add a note about needing jQuery.
