### ISSUE TITLE
Apache Custom Error doesn't work (.htaccess)

### ISSUE THREAD

**Issue by SamAriafar** [h5bp/html5-boilerplate#2261]
I'm using Apache2 on my server and I've followed documentations online and tried all possibilities, but for some reason, ErrorDocument setting doesn't work at all. Just wondering if you have any idea what is going on...

**Comment by roblarsen** [comment]
Hi, while we ship the .htaccess file in this project, it's actually managed in a separate repo- [h5bp/server\-configs\-apache: Apache HTTP server boilerplate configs](https://github.com/h5bp/server-configs-apache) This also seems like it;s more of a stackoverflow thing to me as it may be down to issues with your specific system and not a problem with the project itself.
