### ISSUE TITLE
Unable to add H5BP in frontend repo 

### ISSUE THREAD

**Issue by lambate** [h5bp/html5-boilerplate#2314]
Unable to add H5BP in frontend repo .
no specific documentation available as such which helps in installation of H5BP.
The repo uses docker for deployment.

**Comment by roblarsen** [comment]
What are you trying to do?

**Comment by lambate** [comment]
I have a github repository which runs a dockerfile that uses 'alpine' image. 
I have nginx and npm configured.
now need to configure h5bp in same. However there aren't any specific or clear guideline that would help me configure h5bp.

Thanks for quick revert.

**Comment by roblarsen** [comment]
But what do you want to do with h5bp? How will you use the project? There are commands to run to do different things, I just don't get what the end result you desire is.

**Comment by lambate** [comment]
Need to use it with nginx server.
Basically for much robust frontend websites

**Comment by roblarsen** [comment]
I'll answer the best way I can. There's nothing to configure with this project. We produce a static set of files that represent the baseline for producing a web site or application. 

If you want to serve the H5BP with nginx (or any sever) then you could run 

`npx create-html5-boilerplate`

in the web root folder and then you're done.  The contents of the [dist](https://github.com/h5bp/html5-boilerplate/tree/master/dist) folder will be copied to that folder.

**Comment by lambate** [comment]
Thank you. It worked.
