### ISSUE TITLE
Rename main.css -> style.css in build process + update documentation

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2339]
Re #2323

**Comment by sthiepaan** [comment]
Hello @roblarsen 👋,
I made a _Pull Request_ to resolve this issue. I hope it fits to the requirements/needs.
Feel free to write any comments/suggestions there!

PS: Sorry for not asking before taking care of it 🙈

**Comment by roblarsen** [comment]
Thanks! Looking now!

**Comment by roblarsen** [comment]
closed via #2342
