### ISSUE TITLE
Do we still need plugins.js ?

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2345]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))

There is currently a ['plugins.js' file](https://github.com/h5bp/html5-boilerplate/blob/master/src/js/plugins.js) which [is intended to be used for plugins such as jQuery plugins](https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/js.md#pluginsjs).

In 'plugins.js' there is a 'small script to avoid console errors in browsers that lack a console'. Is that still a useful thing to include? Is this needed for any of our supported browsers? If it's not needed then maybe if it makes sense to either remove this or, if it is needed then perhaps concatenate this file with app.js at build time.

**Comment by roblarsen** [comment]
Probably not!
