### ISSUE TITLE
Move on from Gulp?

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2347]
I have only ever used Gulp in this project. It's also not the shiniest, most modern way to do the tasks we're doing. With the idea that we like to expose best practices, we should do something more modern (and, as a bonus, something I'm more interested in working with, myself. ) 

**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))

**Comment by vltansky** [comment]
I guess Gulp is still the most modern way to maintain this kind of builds (am I wrong?).
Webpack & Parcel not for this kind of builds.
We can develop custom NodeJS build or refactor existing Gulp with async\await and etc.

**Comment by sthiepaan** [comment]
Depends on the roadmap/plans for this project, its complexity and what do we want to solve we should pick the right tools. 
As @vltansky mentioned, we could create own toolkit but at some point I think it is like _"reinventing the wheel"_.

For now, I think that _Gulp.js_ is more than enough. But what we could do is e.g. split the `gulpfile.babel.js` to smaller chunks of code so it is easier to work with (add new tasks, fix/modify existing ones, general maintain)
