### ISSUE TITLE
To Limit Hacktoberfest Spam We Have Temporarily Limited Interactions to Prior Contributors

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2370]
I'm not happy about this, but I'm also not happy about the amount of spam we've received on just the first day, so until someone (GitHub? Digital Ocean)  does something about all the Hactoberfest spam, this is the best I can do.  Beyond the fact that it's annoying to me as the maintainer, we have nearly 3000 watchers. It's not fair to them to get spammed by nonsense. 

Tweet at us at @h5bp, email me (rob at html css javascript dot com) or comment on one of the other repos (main.css or html5boilerplate.com) if you need something and are not a prior contributor.

**Comment by roblarsen** [comment]
Theoretically, Digital Ocean (may they go out of business) has turned off the spam taps as of right about now... We'll see! I might have to turn off contributions again in the morning if any other spammers show up.

**Comment by coliff** [comment]
FYI: https://hacktoberfest.digitalocean.com/hacktoberfest-update

**Comment by roblarsen** [comment]
@coliff I turned it off last night (my time)
