### ISSUE TITLE
Comment-Out Google Analytics Boilerplate

### ISSUE THREAD

**Issue by TensorTom** [h5bp/html5-boilerplate#2379]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (below))

In the greater interest of privacy, many may consider it a bug of a boilerplate lib/repo to contain embedded active scripting from a remote Google property by default. Recommend simply commenting out the script tags with a message such as:

```html
<!-- Google Analytics: Uncomment the code block below & change UA-XXXXX-Y to be your site's ID. -->

<!--
<script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto'); ga('set', 'anonymizeIp', true); ga('set', 'transport', 'beacon'); ga('send', 'pageview')
</script>
<script src="https://www.google-analytics.com/analytics.js" async></script>
-->
```

**Comment by hDmtP** [comment]
"**change UA-XXXXX-Y to be your site's ID.**" - how to be sure that one chooses a unique ID. 
And please can you explain how this scripting will help users privacy?
