### ISSUE TITLE
Creating a repository from a template

### ISSUE THREAD

**Issue by vltansky** [h5bp/html5-boilerplate#2391]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))

I mentioned today that there is a "template repository" (although I understand that it been a long time on GitHub).
https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

So I thought maybe a separate repository from `dist` folder can be used for this? 
See example:
https://github.com/vltansky/html5-boilerplate-template

**Comment by roblarsen** [comment]
👍 We use template repositories at work all the time. I thought about doing it here, but I never followed up on it. I'll set it up. We'll need to create an action that can wrote to it when the main project is updated.

**Comment by vltansky** [comment]
I sent you a request to transfer repo to you.
I'll try to create an action for it, github actions interests me :)

**Comment by roblarsen** [comment]
This is working like magic. 

https://github.com/h5bp/html5-boilerplate-template

Right now it's building based on pushes to master. I might change it to be on release, but I'm not sure right now. We could have the template repo be for people living on the edge and the create script for people who want stability in their lives. 

Thanks @vltansky for the suggestion and getting this work started.

**Comment by roblarsen** [comment]
This is working like magic. 

https://github.com/h5bp/html5-boilerplate-template

Right now it's building based on pushes to master. I might change it to be on release, but I'm not sure right now. We could have the template repo be for people living on the edge and the create script for people who want stability in their lives. 

Thanks @vltansky for the suggestion and getting this work started.
