### ISSUE TITLE
Routing Documentation

### ISSUE THREAD

**Issue by Hakeemmidan** [h5bp/html5-boilerplate#2405]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

Hi,

Thank you for creating this template

Given that the purpose of this is to create a production-ready website as fast as possible, I suggest adding some documentation in regards to frontend routing as I (a beginner) felt that was somewhat missing

I'm not sure if this can already be done without adding packages or not, but either way, I think it may be a good idea to add some instructions around it in the README to get people up and going at an even faster speed 

Just a thought
Thank you

**Comment by roblarsen** [comment]
I'm sorry- we don't offer routing as a feature, so I'm not sure what there would be to document.

**Comment by Hakeemmidan** [comment]
Hi Rob,

Thank you for your quick response

I see. Nevertheless, I still think it may be a good idea to add some 'suggested tools' documentation (or something along those lines) to point users of the template in the right direction. Frontend routing is an integral part of any website, and I believe that this suggestive documentation will go along with this template's mission. But that's of course up to the maintainers' preference

As for suggestions, I don't have any exact tools in mind. I tried implementing [Navigo](https://github.com/krasimir/navigo) in `js/main.js`, but it proved to be too troublesome. I imagine heavy users of the template may have better suggestions

Nevertheless, feel free to close this issue if you don't see this suggestion fitting in with HTML5 Boilerplate's objectives

**Comment by roblarsen** [comment]
I don't think we'll be doing that. I don't know of a situation where I would implement a standalone routing library. If you're doing a single page application chances are pretty good you're using a framework or library that provides this functionality. For an example, I know an awful lot about routing in Angular. Documenting that here wouldn't make sense. 

Thanks for the thoughtful suggestion!
