### ISSUE TITLE
load third-part js lib which download into vendor are faild 

### ISSUE THREAD

**Issue by july-12** [h5bp/html5-boilerplate#2407]
## why to load third-party js lib(eg: Threejs, react) always are faild  except loading from CDN

![image](https://user-images.githubusercontent.com/920487/99770930-39f39500-2b43-11eb-8e98-b97c69a744a2.png)

**Comment by roblarsen** [comment]
Is the file in your vendor folder? There's nothing stopping you from loading a file from your file system.
