### ISSUE TITLE
I got the front page on the server but no working site just "Hello world! This is HTML5 Boilerplate." http://localhost:1234/

### ISSUE THREAD

**Issue by AusGirl** [h5bp/html5-boilerplate#2439]
I got the front page on the server but no working site just "Hello world! This is HTML5 Boilerplate." http://localhost:1234/

So, where is the website? what should I do to view it? I'm on VSCode

**Comment by roblarsen** [comment]
Hi, that's the website. The only content we [ship with is that paragraph](https://github.com/h5bp/html5-boilerplate/blob/master/dist/index.html#L28)

I'm not sure what else you expect to see.

**Comment by AusGirl** [comment]
help me :( I'm so confused of this GITHUB, youtube also doesn't have any videos of how to run github codes

**Comment by roblarsen** [comment]
What are you trying to do?

**Comment by AusGirl** [comment]
I'm trying to find a html css editor and found this GITHUB page, and I tried to run this in VSCODE and it just shows "Hello world! This is HTML5 Boilerplate.". I don't know how to view the editor being developed here.

**Comment by roblarsen** [comment]
This is not an editor. It is a simple template for you to start creating a web site or application. You would use an editor like VS Code to edit the files to create your own site. HTML5 Boilerplate is probably not what you're looking for.
