### ISSUE TITLE
Feature Request - Use Of A Different Reseter/Normalizer

### ISSUE THREAD

**Issue by krishdevdb** [h5bp/html5-boilerplate#2447]
**I'm submitting a feature request**

## Feature requests

Normalize CSS Has A Lots Of Issues And It is really popular and used across many sites plus it's heavy. Because Of That Our Sites Look Similar To Other Sites And They Are Heavy As Well. So, I Suggest That If We Need A Simple Reset. We can use something like [minireset.css](https://github.com/jgthms/minireset.css) by [jgthms](https://github.com/jgthms). If We Need A CSS Normalizer We Can Use Something Like [Sanitize.css](https://github.com/csstools/sanitize.css) or [Bootstrap's Reboot](https://github.com/twbs/bootstrap/blob/main/scss/_reboot.scss)

**Comment by roblarsen** [comment]
I think we're going to stick with normalize right now. Normalize is fruit of the same open source family tree as HTML5-Boilerplate so unless there's a real problem with it, I'm happy to stick with it.
