### ISSUE TITLE
Review Modernizr Config, docs and update to 3.12.0

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2548]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

We currently include Modernizr and a custom config which hasn't been update for 4 years. I think we should review the config and remove anything that isn't needed for our supported browsers. At a quick glance I would imagine css/flexbox and css/animations could be safe to remove since they are both well supported in all browsers (including IE 11).

The relevant Modernizr docs need some updates too:
https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/html.md#modernizr
No need to mention HTML5 Shiv since it hasn't been needed since IE 9 and I think we should avoid linking to the [Mondernizr website](https://modernizr.com/) since it is no longer updated. Instead we should just link to the [GitHub repo](https://github.com/modernizr/modernizr).

**Comment by roblarsen** [comment]
+1 I'll take a look at this
