### ISSUE TITLE
Suggest remove 'Common Prefetch Links' from docs

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2549]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request
- [ ] other (Please do not submit support requests here (below))

https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/extend.md#common-prefetch-links

I don't think these are very helpful.

- Google's hosted libraries CDN isn't as popular as it once was.
- Users probably shouldn't be serving content directly from s3.amazonaws.com (it's not a CDN) and instead have CloudFront in front of it.
- Microsoft are actively discouraging users from using the Microsoft one. (https://docs.microsoft.com/en-us/aspnet/ajax/cdn/overview) and I agree with their statement: 'Production applications should not take a hard dependency on 3rd party CDN assets.'

It's easy enough for a user to add a preconnect themselves and there are already a couple of examples directly above: https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/extend.md#explicit-prefetches

**Comment by roblarsen** [comment]
I didn't remember that we had that. 100%
