### ISSUE TITLE
RFC: Remove Separate mobile URLs docs

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2550]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

Google doesn't recommend separate URLs as a site setup and it isn't common these days (responsive design has largely replaced it). I think we should consider removing this section from the Extend docs.
https://github.com/h5bp/html5-boilerplate/blob/master/src/doc/extend.md#separate-mobile-urls

**Comment by roblarsen** [comment]
👍

**Comment by coliff** [comment]
I'll take care of this one.
