### ISSUE TITLE
RFC: Remove human.txt ?

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2553]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

A `humans.txt` file is included by default in the project. I don't think this is an important file to include and not really suitable for all sites. It can be a nice thing to include for some sites but overall I think we should cover it in the docs but not include the file by default. Open to opinions on this from others!

**Comment by mfurkan60** [comment]
I think we should create a Requirements folder (or whatever names) in the project. Can we keep the files that are not mandatory but that people need when necessary? We should keep files like human.txt in the required folder.

**Comment by goellavish10** [comment]
I think we should mention the names and technologies used in the documentation instead. Users will most probably be deleting the humans.txt file when using this project.

**Comment by roblarsen** [comment]
@goellavish10 I'm pretty sure @coliff was talking about adding `humans.txt` to the documentation. We already document everything we do in terms of building the project. I quite like humans.txt, but I'm fine with getting rid of it as well.
