### ISSUE TITLE
Sass Folders to the CSS folder?    

### ISSUE THREAD

**Issue by mfurkan60** [h5bp/html5-boilerplate#2560]
I think we should add Sass Folders to the CSS folder?
 and that situation can make the project more modern?

**Comment by roblarsen** [comment]
We could call it `styles` which would make it more generic.

**Comment by zourdycodes** [comment]
before creating the folder I think we have to make sure it's not gonna make any conflicts with the current style folder

**Comment by isaac-friedman** [comment]
> before creating the folder I think we have to make sure it's not gonna make any conflicts with the current style folder

Happy to help look through the code for conflicts but where would `style` in singular conflict with `styles` plural, or are you talking about a different issue?

**Comment by roblarsen** [comment]
I'm not sure what conflicts there might be.

**Comment by zourdycodes** [comment]
> > before creating the folder I think we have to make sure it's not gonna make any conflicts with the current style folder
> 
> Happy to help look through the code for conflicts but where would `style` in singular conflict with `styles` plural, or are you talking about a different issue?

LOL I didn't see it as a plural or singular, my bad : )

**Comment by roblarsen** [comment]
This will all be sorted out. Thanks!
