### ISSUE TITLE
Parcel v1 is no longer maintained

### ISSUE THREAD

**Issue by weirdyang** [h5bp/html5-boilerplate#2568]
**I'm submitting a ...**

-[ ] bug report
-[ ] feature request
-[x] other (Please do not submit support requests here (below))

On the npm site for parcel-bundler, there's a note:

`Parcel v1 is no longer maintained. Please migrate to v2, which is published under the 'parcel' package. See https://v2.parceljs.org/getting-started/migration for details.`

Are there any plans to migrate to v2?

**Comment by roblarsen** [comment]
We have thoughts? #2487
