### ISSUE TITLE
Update ESLint

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2624]
There was recently a major update to ESLint.
https://eslint.org/blog/2021/10/eslint-v8.0.0-released

We should update to it and ensure all tests pass.

**Comment by roblarsen** [comment]
@isaac-friedman still want to take this?

**Comment by isaac-friedman** [comment]
@roblarsen  sorry, my day job got a little busy. I should probably withdraw if it's time sensitive

**Comment by roblarsen** [comment]
@isaac-friedman no worries. I'm just working my way through issues right now.
