### ISSUE TITLE
Manifest Shortcuts

### ISSUE THREAD

**Issue by inetbiz** [h5bp/html5-boilerplate#2628]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

## Append Main

Shorts are W3C compliant. [*Adding shortcuts*](https://www.w3.org/TR/appmanifest/#creating-shortcuts "webmanifest Shortcuts")

### Example
```json
{
  "shortcuts": [
    {
      "name": "Play Later",
      "description": "View the list of podcasts you saved for later",
      "url": "/play-later",
      "icons": [
        {
          "src": "/icons/play-later.svg",
          "type": "image/svg+xml"
        }
      ]
    },
    {
      "name": "Subscriptions",
      "description": "View the list of podcasts you listen to",
      "url": "/subscriptions?sort=desc"
    }
  ]
}
```
Just below https://github.com/h5bp/html5-boilerplate/blob/main/src/site.webmanifest#L3 add: 
`lang": "xx_XX",` **en_US**
Shortcuts are not necessarily for apps. I think it's relatable to https://schema.org/significantLinks

**Comment by roblarsen** [comment]
I would be interested in seeing more examples of what sort of things you can do with a manifest. We could add that to the documentation. 

We do **not** add language encoding to files, by default. People don't change them, which can result in unexpected behavior.

**Comment by inetbiz** [comment]
> I would be interested in seeing more examples of what sort of things you can do with a manifest. We could add that to the documentation.
> 
> We do **not** add language encoding to files, by default. People don't change them, which can result in unexpected behavior.

Well if you make it clear that this is merely a recipe and that a link to the ISO standard is what they would replace. But, I understand.

Shortcuts become deep links. They prompt smart devices that they may also use those links as a starting URL instead of the primary. So if I had a collection of “Gardening tips” I can select that as the starting URL because it was defined in the shortcuts

**Comment by roblarsen** [comment]
It's a long-standing issue. We don't add language information. We try to cause the least harm. And no language information is better than the wrong language.

**Comment by inetbiz** [comment]
Ok How about a compromise? Comment the line out. Add to your README or
other document to uncomment and show a link to where they can complete the
entry? =)

**Comment by roblarsen** [comment]
We don't ship commented out code. People don't always change things, so shipping commented out code means we just ship unnecessary bytes. This would be good information for the extend documentation.

**Comment by inetbiz** [comment]
We'll stick w/ shortcuts feature?

**Comment by roblarsen** [comment]
> This would be good information for the extend documentation.

Sorry, if I haven't been clear. I'm only interested in potentially adding documentation. We will not ship a manifest to people that has nonsensical information. I got sidetracked by the proposal to add "en" to the language.
