### ISSUE TITLE
Missing .mov?

### ISSUE THREAD

**Issue by nielsjakob** [h5bp/html5-boilerplate#2649]
**I'm submitting a feature request**

Wondering why there's no mention of `mov`? Is this missing on purpose? Otherwise it would be great to add it :)

**Comment by coliff** [comment]
what do you mean by missing `mov`? Can you please explain further?

**Comment by coliff** [comment]
ah I see. Please could you open an issue at: https://github.com/h5bp/server-configs-apache ?
thanks!
