### ISSUE TITLE
Create WebPack build to build the project?

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2651]
related to #2347 

If #2650 is clean and tidy then, I guess so.

**Comment by darkknight20032001** [comment]
is anyone working on this issue?

**Comment by roblarsen** [comment]
@darkknight20032001 no. I'd be happy to work with you if you want to take a shot

**Comment by darkknight20032001** [comment]
> @roblarsen gr8 thanx a lot.... can we start???

**Comment by darkknight20032001** [comment]
@roblarsen this is my first open source experience. Can u provide details to me pls???

**Comment by roblarsen** [comment]
@darkknight20032001 The goal of this issue is to replace [html5\-boilerplate/gulpfile\.babel\.js at main · h5bp/html5\-boilerplate](https://github.com/h5bp/html5-boilerplate/blob/main/gulpfile.babel.js) with WebPack. 

The script does the following:

-  zips up the contents of the `dist` directory (minus `node_modules`, `package-lock.json`, `.cache`, and `dist`) and outputs it with the following pattern (Where `pkg` is the contents of the project package.json file) `${pkg.name}_v${pkg.version}.zip`
- copies the contents of `node_modules/apache-server-configs/dist/.htaccess` to the dist folder
- copies the `index.html` folder from `src` to `dist` and replaces  MODERNIZR_VERSION with the latest version of Modernizr.
- copies `LICENSE.txt`
- copies the style sheet from `node_modules/main.css/dist/main.css` to `dist/css/style.css` and adds a banner (`/*! HTML5 Boilerplate v${pkg.version} | ${pkg.license} License | ${pkg.homepage} */\n\n`) to the file
- copies everything else over
- builds modernizr

The process would be to create a fork of this repo, create a branch where you will do this work and as soon as you have something to show, open a pull request here. Assign me as a reviewer and mark the PR as a "draft" Once I can see your code here I'll work with you here on GitHub
