### ISSUE TITLE
Update docs to focus on the difference between this repo and the project as end-users use it

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2652]
We need to do a much better job of describing the difference between this project and the **output** of this project, which is the thing that people actually use.  

For example, the gulpfile is used by basically two people most of the time, me and @coliff (as well as any kind contributors who notice that we need to run a build 🥇) It's a tool used to **build** HTML5 Boilerplate, its not part of the thing that we ship. So when Chris Coyier pointed it out in an article last year it was like a bolt of lighting to my brain that we needed to reposition the way we present the repo. 

The thing we ship is the [dist](https://github.com/h5bp/html5-boilerplate/tree/main/dist) folder of this repo, the [npm package](https://www.npmjs.com/package/html5-boilerplate), the output of [create-html5-boilerplate](https://github.com/h5bp/create-html5-boilerplate) and, breaking news, the [template repository](https://github.com/h5bp/html5-boilerplate-template) we just launched.

I need to write those words in the readme. 

(not those exact words, but words like them. Just better)

**Comment by coliff** [comment]
Also, related - we should definitely move the `docs/` dir out of `src/` and `dist/` to the root so they aren't duplicated.

**Comment by princek096** [comment]
Hello Sir, can i work on this issue?

**Comment by roblarsen** [comment]
Thanks, this one needs to be done by me.
