### ISSUE TITLE
Shoud .DS_Store files be automatic ignored? 

### ISSUE THREAD

**Issue by jeanlucaslima** [h5bp/html5-boilerplate#2653]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

Should `.DS_Store` files be automatically ignored by the boilerplate?

**Comment by roblarsen** [comment]
Ignored how?

**Comment by coliff** [comment]
Yes, I think they should be added to `.gitignore`

**Comment by roblarsen** [comment]
If that's the case, then yes, but it also leads to the question of why we ship such a meager .gitignore with the project.

**Comment by jeanlucaslima** [comment]
@roblarsen well, there's already a `.gitignore` file with some standards like `node_modules` included. I don't see why not add `.DS_Store` so the Mac users out there won't commit it by mistake.

**Comment by roblarsen** [comment]
@jeanlucaslima I see that, thanks for the PR. I was asking because there are actually two pertinent `.gitignore` files in the project, one in the root folder for development of this project and one that we ship in `/dist/` which is the example `gitignore` we ship with the project.

**Comment by jeanlucaslima** [comment]
@roblarsen perfect! And thanks for merging. 

Let me see if I get this right: the one in `/dist/` is the one available for download on the website? 
If not, and the person gets the root one it means all `.DS_Store` files will be ignored and never committed by accident, which is the goal here.

**Comment by roblarsen** [comment]
@jeanlucaslima Yes, you've changed it for people working on the project, which is good. 

It also got me thinking about the gitignore that we ship with the download file.  Which is also good. 

So, thanks!
