### ISSUE TITLE
Questions 

### ISSUE THREAD

**Issue by BenRacicot** [h5bp/html5-boilerplate#2712]
I'm creating an issue here because I'm not only confused about how to work with the boilerplate but IMO the setup is not what web engineers expect at first glance.

Why is `dist` shipped to `main`? Typically we don't commit `dist` folders.
In `main` the CSS folder mentioned in usage.md does not exist? To create it would be strange because this is a boilerplate meant to pull-and-go. It's also confusing because dist exists, with these compiled files. Very confusing.
Since webpack is included and even setup for builds maybe we can consider TypeScript compilation?

Thanks for reading.

**Comment by roblarsen** [comment]
This is where HTML5 Boilerplate is built. To use the output of the project, try the options listed in the Quick Start section of the Readme (pasted below) 

There is an open issue for me to make that more clear although it's the same as any other project. You don't check out [https://github.com/facebook/react](https://github.com/facebook/react) to use React. 


## Quick start

Choose one of the following options:

* Download the latest stable release from
  [html5boilerplate.com](https://html5boilerplate.com/). This zip file is a
  snapshot of the `dist` folder. On Windows, Mac and from the file manager on
  Linux unzipping this folder will output to a folder named something like
  `html5-boilerplate_v7.3.0`. From the command line will need to create a
  folder and unzip the contents into that folder.

  ```bash
  mkdir html5-boilerplate
  unzip html5-boilerplate*.zip -d html5-boilerplate
  ```

* Clone the git repo — `git clone
  https://github.com/h5bp/html5-boilerplate.git` - and checkout the
  [tagged release](https://github.com/h5bp/html5-boilerplate/releases)
  you'd like to use. The `dist` folder represents the latest version of the
  project for end users.

* Install with [npm](https://www.npmjs.com/): `npm install html5-boilerplate`
  or [yarn](https://yarnpkg.com/): `yarn add html5-boilerplate`. The resulting
  `node_modules/html5-boilerplate/dist` folder represents the latest version of
  the project for end users. Depending on what you want to use and how you want
  to use it, you may have to copy and paste the contents of that folder into
  your project directory.

* Using the [create-html5-boilerplate](https://github.com/h5bp/create-html5-boilerplate)
  script, instantly fetch the latest npm published package (or any version
  available on npm) with `npx`, `npm init` or `yarn create` without having to
  install any dependencies. Running the following `npx` command installs the
  latest version into a folder called `new-site`

  ```
  npx create-html5-boilerplate new-site
  cd new-site
  npm install
  npm run start
  ```

* Using our new [Template Repository](https://github.com/h5bp/html5-boilerplate-template)
  create a new GitHub repository based on the latest code from the main branch of HTML5
  Boilerplate.

**Comment by BenRacicot** [comment]
Hey Rob! Thanks for pasting that in here. I had read all of that previously but just wanted to hear your opinion on pulling main and experiencing what I described.

Could you also give some details on setting up **scss**?

**Comment by roblarsen** [comment]
Yeah, it's been an issue for a while #2652 I just haven't had time to get it up and running.

I can write up setting up scss for the docs. I have wanted to add some new how-tos to the docs.

**Comment by BenRacicot** [comment]
If I knew how to configure the webpack config I would commit the PR.

If I can help please let me know how. Otherwise perhaps I can buy you a coffee for setting that up for all of us h5bp users?
