### ISSUE TITLE
update supported node versions

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2717]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))

The node versions in package.json and tests reference old, unstable versions (v10 and v12).
I suggest we update them to active versions.
https://nodejs.org/en/about/releases/

**Comment by NehaK275** [comment]
hi @coliff can i solve this?

**Comment by coliff** [comment]
heya @NehaK275 - its ok now thanks. I'll make a PR for it now. :-)
