### ISSUE TITLE
Remove `.htaccess` from dist?

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2718]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))

We currently ship a `.htaccess` file for Apache servers which is a really helpful file for Apache servers, but I think many/most sites built today are not necessarily hosted on a server. With the advent of serverless I suggest that we no longer need to include this file by default.

If removed we should certainly make a mention that we have great starter server configs available via our sister projects: https://github.com/h5bp?q=server&type=source&language=&sort=stargazers

**Comment by roblarsen** [comment]
I'd buy that. I would like to add an option to the create script to pull in the apache or nginx config. Let me create an issue over there to track that.
