### ISSUE TITLE
This repo keeps appearing on my Github main page?!?

### ISSUE THREAD

**Issue by raquelocasio** [h5bp/html5-boilerplate#2728]
This repo keeps appearing on my Github main page, but I have not forked or starred it. Can someone please remove me from this repo's subscriber list?

**Comment by oriolaakeem** [comment]
Go to the email and click on the unsubscribe link.

**Comment by roblarsen** [comment]
We can't add anyone without their permission to our subscriber list.  

If you see an "unwatch" button or a filled-in star when you view our repo, that means you are watching it (which is the same as subscribing) or starred it (which is much less noisy)  

![image](https://user-images.githubusercontent.com/361421/158434696-f6cdbf43-dea8-41c0-83de-5cd63811f8e7.png)

Looking at your profile, I wonder if you are seeing the default behavior for people that don't have many interactions yet on GitHub. You don't follow any users and have only starred 3 repos. GitHub has to show you something, I guess and they chosen this popular repo as one of the options. Usually that space on your homepage is for seeing what people you follow are doing.  I can't control what content goes on that page. That's in GitHub's hands.
