### ISSUE TITLE
Use actions to label and milestone across repos

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2749]
Since so many of our repos need to be updated to properly craft a release here, we should be able to set labels and milestones across repos. This is doable with Actions (and is coming at some point, I think.)

**Comment by roblarsen** [comment]
It looks like we'll be able to create custom workflows in GitHub projects that will allow this to happen, GitHub native:

![image](https://user-images.githubusercontent.com/361421/164071923-c59c0473-a79e-4b86-bfc0-468c1a091868.png)

**Comment by coliff** [comment]
Yes, I'm really looking forward to those custom workflows!
