### ISSUE TITLE
Use GitHub Issue Form Templates

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2751]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

[GitHub offers neat Issue templates](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/). You can have required checklists so users can't ignore that they've read through the issue requirements. I think it would be very helpful to add 'Bug Report' and 'Request Feature' forms. A user will still have the option to create a new blank issue if necessary.

I'm hopeful this will cut down on back and forth requesting more info for bug reports as well as hopefully cutting down on users testing issues without adding anything which creates extra noise for everyone.

A user is already expected to check if an issue has been opened already before creating a new one but unfortunately our [closed issues are full of users testing](https://github.com/h5bp/html5-boilerplate/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed) which makes it more of a hassle. :-(

I've recently created some forms for some other open source projects so I'll open a PR for this.

**Comment by roblarsen** [comment]
Closed via: [Merge pull request \#2932 from h5bp/issue\-template · h5bp/html5\-boilerplate@48f92c4](https://github.com/h5bp/html5-boilerplate/commit/48f92c41cd8ee7d15b3db2f39676169bd71a5416)
