### ISSUE TITLE
Apply New or Neglected Best Practices to the Repo

### ISSUE THREAD

**Issue by roblarsen** [h5bp/html5-boilerplate#2764]
And document them!

Hopefully thoughtful configuration of this and other repos will help others do the same. I have lagged behind the standards I've set in my professional projects with the configuration of the H5BP repos.

**Comment by roblarsen** [comment]
This is actually done, I just need to document it, but the branch protection rules are blocking the automatic dist build. 🤔

**Comment by roblarsen** [comment]
https://github.com/h5bp/html5-boilerplate/runs/6777433545?check_suite_focus=true

😭

**Comment by roblarsen** [comment]
https://github.com/github-community/community/discussions/13836

https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101

**Comment by sahilulhaque17** [comment]
Gut pull

**Comment by sahilulhaque17** [comment]
Git pull
