### ISSUE TITLE
Farewell Internet Explorer!

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2773]
**I'm submitting a ...**

- [ ] bug report
- [x] feature request
- [ ] other (Please do not submit support requests here (below))

[The Internet Explorer 11 desktop application will end support for Windows 10 semi-annual channel starting June 15, 2022.](https://docs.microsoft.com/en-us/lifecycle/products/internet-explorer-11)

It'd make sense for HTML5 Boilerplate to drop support for IE11 in the next major version.

Changes we'd be able to make:

- Remove docs about Pinned sites for Windows from the **extend** docs
- Remove note about 'encoding-related security issue' from **HTML** docs
- Remove `browserconfig.xml` from the project
- Edit supported browsers in `package.json` to remove IE11

**Comment by roblarsen** [comment]
Let us do this.

**Comment by roblarsen** [comment]
closed via #2781

**Comment by roblarsen** [comment]
I just can't hide it.

**Comment by coliff** [comment]
yep, it's amazing thinking back to the browser landscape when [HTML5 Boilerplate started in Summer 2010](https://github.com/h5bp/html5-boilerplate/wiki/history) and seeing how predominant IE was.

![image](https://user-images.githubusercontent.com/1212885/172423961-fbdd7b08-6e4d-492a-80ac-0d3bb5add334.png)

from: https://gs.statcounter.com/browser-version-partially-combined-market-share/desktop/worldwide/#monthly-201007-201007-bar

**Comment by frenzzy** [comment]
Should we also delete `tile-wide.png` and `tile.png`?

**Comment by coliff** [comment]
> Should we also delete `tile-wide.png` and `tile.png`?

Yes, you're right, we should. We are due a major release - it's been a long while since v8.0 shipped!

**Comment by bautisj** [comment]
yeah

**Comment by roblarsen** [comment]
It's basically the build stuff, I think. I'll take a look.
