### ISSUE TITLE
SASS/SCSS Support 

### ISSUE THREAD

**Issue by momin-riyadh** [h5bp/html5-boilerplate#2840]
**I'm submitting a ...**

- [ ] feature request

## Feature requests

It would be better for boilerplate to offer full support for SASS/SCSS configurations

**Comment by roblarsen** [comment]
@momin-riyadh What would you expect that support to look like?

**Comment by momin-riyadh** [comment]
Like l run a command line from parcel bundler and my scss file compile simultaneously.

**Comment by roblarsen** [comment]
Thanks. The CSS files that are there would not benefit from being SCSS files (I've experimented with it) but if the basic workflow was beneficial I wouldn't be against it. But I've actually look ed at converting the source files to being SCSS natively and there's no benefit other than the plumbing,

**Comment by roblarsen** [comment]
Parcel is being removed from the project.

**Comment by momin-riyadh** [comment]
One more thing I can say is that all the `.html` extension files should reload. Suppose I work on `index.html` and finish and I create a copy of `index.html` and rename the `post.html` and work on it, it should also reload on the browser on the gulp command, and every change
