### ISSUE TITLE
[question] How to publish static assets?

### ISSUE THREAD

**Issue by xididri** [h5bp/html5-boilerplate#2876]
**I'm submitting a ...**

- [ ] bug report
- [ ] feature request
- [x] other (Please do not submit support requests here (below))

How to I make static assets available on the published website? I want to publish at mywebsite.com/some-image.png so I can use it as an OpenGraph image (which does not allow relative URL).

I tried to create a `public` folder and a `static folder` but they are not copied on build.

I feel this info should be in HTML5Boilerplate docs.

*Sorry in advance if missed it but I read the docs (I checked the README, [Usage](https://github.com/h5bp/html5-boilerplate/blob/main/docs/usage.md), the [FAQ](https://github.com/h5bp/html5-boilerplate/blob/main/docs/faq.md) [Miscellaneous](https://github.com/h5bp/html5-boilerplate/blob/main/docs/misc.md) and [Extending](https://github.com/h5bp/html5-boilerplate/blob/main/docs/extend.md)), I searched [Parcel docs](https://parceljs.org/docs/), [Github Issues](https://github.com/h5bp/html5-boilerplate/issues/) issues, [SO](https://stackoverflow.com/questions/tagged/html5boilerplate).*

**Comment by roblarsen** [comment]
Parcel is dumb #2487

**Comment by roblarsen** [comment]
We're replacing it, but I've been terrible at getting this release out the door.

**Comment by roblarsen** [comment]
👀 #2650

**Comment by roblarsen** [comment]
`npm run build` now does it. 

I will release this within the next couple of weeks.

**Comment by xididri** [comment]
@roblarsen thank you very much, that did the trick!
