### ISSUE TITLE
Create a GitHub new issue form

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#2931]
Our issue tracker is unfortunately being inundated with tests and spam.
https://github.com/h5bp/html5-boilerplate/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed

This has many negative effects and makes it more difficult for genuine issues to be searched for.

I think we should create a new form using YAML (https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms). This has many advantages over a freeform markdown file as users would need to confirm that it is a genuine issue. (checkboxes on the form can be set to be required)

Here's a few examples of good GitHub forms:
- https://github.com/twbs/bootstrap/issues/new?assignees=-&labels=bug&template=bug_report.yml&title=Provide+a+general+summary+of+the+issue
- https://github.com/FortAwesome/Font-Awesome/issues/new?assignees=&labels=bug%2Cneeds-triage&template=100_web_bug_report.yml&title=Bug%3A+

**Comment by roblarsen** [comment]
I will do this!
