### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#3009]
### Prerequisites

- [X] I have [searched](https://github.com/h5bp/html5-boilerplate/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)

### Proposal

It can be a bit annoying when the formatting of code changes a bit with PRs. I think it'd be good to add Prettier as a dev dependency and add the following script to package.json

```json
"prettier": "prettier --write ./*.{js,json,md,yml}"
```

We should ignore the dist folder though.

### Motivation and context

Keeps docs and code formatted consistently and prettier.

**Comment by roblarsen** [comment]
That's fine with me.
