### ISSUE TITLE
npm run test failing

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#3015]
`npm test` is failing for me (Windows 10, node v18.17.1).

Strange because npm test is run as a GitHub Action and hasn't failed.
e.g. https://github.com/h5bp/html5-boilerplate/actions/runs/6116096003/job/16600771514

![image](https://github.com/h5bp/html5-boilerplate/assets/1212885/e6548fab-7ac0-4ffc-bc8c-3c5400528e94)

**Comment by roblarsen** [comment]
super weird

**Comment by coliff** [comment]
it works fine on my Mac. I'll close this for now and do more investigation.
