### ISSUE TITLE
update twitter card docs

### ISSUE THREAD

**Issue by coliff** [h5bp/html5-boilerplate#3026]
### Prerequisites

- [X] I have [searched](https://github.com/h5bp/html5-boilerplate/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)

### Describe the issue

https://github.com/h5bp/html5-boilerplate/blob/main/docs/extend.md#twitter-cards

Twitter card docs need updating (or removing)
- name change to X
- Card validator no longer works so should remove the link 

### Reduced test cases

N/a

### What operating system(s) are you seeing the problem on?

Windows

### What browser(s) are you seeing the problem on?

Microsoft Edge

### What version of HTML% Boilerplate are you using?

Latest

**Comment by pragyamishra56** [comment]
This is my first open source and I would like to contribute in every way possible. If you can guide and assign this to me

**Comment by coliff** [comment]
> This is my first open source and I would like to contribute in every way possible. If you can guide and assign this to me

thanks for the offer! I'll take care of this one though as I know exactly what needs to be changed.

**Comment by pragyamishra56** [comment]
@coliff If it is still open can I work on this issue if would be possible Sir

**Comment by roblarsen** [comment]
@pragyamishra56 it doesn't work like that. We're not in the business of giving people permission to work on issues. If you want to work on an issue, just work on it and open a PR. I will say that taking on documentation tasks isn't great, unless you're used to writing a lot of documentation.
