### ISSUE TITLE
Normalize.css still referenced in index.html

### ISSUE THREAD

**Issue by rgant** [h5bp/html5-boilerplate#3033]
https://github.com/h5bp/html5-boilerplate/blob/87bdc80ab9e35dcb52d75ffc926d8ed67991c626/src/index.html#L19

Removed in #2960

**Comment by roblarsen** [comment]
This would make a great PR for someone.

**Comment by roblarsen** [comment]
Nice one @rgant I didn't even have time to add the help-wanted tag
