### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Tsiangana** [h5bp/html5-boilerplate#3079]
### Prerequisites

- [X] I have [searched](https://github.com/h5bp/html5-boilerplate/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)

### Proposal

I really liked the project, but as a user of it I think it could be a little better, something kind of basic, that is, an idea I had based on other sites.

What do you think, instead of when you click on get starded it takes you directly to the github readme documentation, you could create a tab on the same site where you would place get starded in a more stylized way. If you don't have time to do it, I can make a fork and then you can analyze it, if you like it, add my fork, if not, you can make an issue and tell me what you didn't like or what I can improve, I have experience in UI/UX design so I guarantee to do a good job.

Tell me what you think

### Motivation and context

I think this is relevant because it is something more common which makes it easier for users, as users we don't all like when we are on a website and we click on a button it takes us to another location to continue the project, sometimes this irritates and It makes you lose the desire to actually test the project, which is why many sites add documentation directly to the site in question.

**Comment by jan-queralt** [comment]
i can help you if u want, i have experience
