### ISSUE TITLE
Add a File/Folder structure

### ISSUE THREAD

**Issue by Yuheshpandian** [h5bp/html5-boilerplate#3082]
### Prerequisites

- [X] I have [searched](https://github.com/h5bp/html5-boilerplate/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
- [X] I have read the [contributing guidelines](https://github.com/h5bp/html5-boilerplate/blob/main/.github/CONTRIBUTING.md)

### Proposal

I think that adding a seperate .md document for file/folder structure of the boiler plate or adding it on the README is very crucial for a boler plate, that everyone wants to use in their project. This is because people are very much lazy to create a proper file structure for their sites and thats why many pros opt to boilerplate for its features and readily available file structure.

### Motivation and context

This is followed in many boilerplates so that people might get the value of the boilerplate in glance. So this is very important for a boilerplate in my opinion.

**Comment by roblarsen** [comment]
We have a well thought out folder/file structure and document the folder/file structure.

**Comment by Yuheshpandian** [comment]
Yeah finally found it thanks for the help....[Structure](https://github.com/h5bp/html5-boilerplate/blob/main/docs/usage.md)
