### ISSUE TITLE
Extra .htaccess rules for flexible filenames to cache-bust

### ISSUE THREAD

**Issue by marceltt** [h5bp/html5-boilerplate#355]
Whether commented out by default or not, I think the following rules will make a nice addition to the .htaccess file.

```
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.+)\.(\d+)\.(js|css|png|jpg|gif)$ $1.$3 [L]
```

Added to the top of a mod_rewrite set of rules, they make it so you can reference a JS/CSS/image file with a version/timestamp inserted before the file extension. So for example, a request for `/res/all.20110203.css` will instead serve up `/res/all.css`. This will resolve the potential problem of files with query strings being mis-cached.

Hat-tip: http://wiki.typo3.org/TYPO3_4.4

**Comment by matthew-dean** [comment]
Just curious, how would you request a file that had something like file.min.js? Is it file.min.0.js or file.0.min.js?

**Comment by alrra** [comment]
>  Is it file.min.0.js or file.0.min.js?

@matthew-dean `file.min.0.js` (basically `file.min.<number>.js`).

**Comment by matthew-dean** [comment]
Ah thanks. I figured that out but forgot to update here. I did have this fail for this:

```
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.1.0.css">
```
I assume it fails because the version number in the path.

**Comment by alrra** [comment]
```html
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.1.0.css">
```

@matthew-dean  :arrow_up: That file is on the jQuery CDN, so your server configs do not apply to it. :)

**Comment by matthew-dean** [comment]
> @matthew-dean  :arrow_up: That file is on the jQuery CDN, so your server configs do not apply to it. :)

Ohhhhhh right duh. * facepalm *
