### ISSUE TITLE
mobile/iOS css revisions

### ISSUE THREAD

**Issue by paulirish** [h5bp/html5-boilerplate#37]
(I have revised this ticket summary after the issue has been fixed for clarity)
- Scott jehl was concerned with maximum scale = 1
- @riddle posted a few concerns as well.. "No scaling, no text adjustment?"

After discussions with Matt Henry, a front-end dev mobile expert, recently from Yahoo!, now at Viget...
We concluded to drop maximum-scale=1 and leave text-size-adjust commented out by default.

max-scale doesnt let the user zoom in as they please. However it prevents some weird layout shifting when a device is changed from portrait to landscape. It doesn't seem like a good default.

initial-scale remains 1. It's default is 'auto' and I have no understanding why a mobile browser would set it to anything other than 1, but it's explicitly set for now..

Also.. worth watching http://people.opera.com/rune/TR/css-viewport/ (though it's unimplemented anywhere so far)

**Comment by Kusadam** [comment]
I tried all but nothing [http:/kusadam.com](url)
