### ISSUE TITLE
::selection background color default

### ISSUE THREAD

**Issue by necolas** [h5bp/html5-boilerplate#610]
The issue of the `::selection` styles has been brought up again, this time in tweets from [Paul Lloyd](https://twitter.com/paulrobertlloyd/status/93265698800934912) and [Stu Robson](https://twitter.com/StuRobson/status/93258457490268160) (unless that last tweet is actually about the old `tap-highlight-color` style).

As far as I can tell, their concerns seem to be about the default `background` pink being a poor default colour. Hopefully they can provide any further descriptions and suggestions.

In terms of colour contrast, last time I checked, the "hot pink" is no better or worse than the default blue used by browsers - 3.0:1. I think the removal of `text-shadow` when text is highlighted is a good improvement, so the only alternative I can see it to switch the background to using the default blue - `#3297FD` - and/or to include a comment alongside the rule to say something.

**Comment by innovandrew** [comment]
I have probably lost 80 hours of my life changing this back to hot pink.

Every time I have to find this thread to get the color code.

I don't care why I shouldn't be setting it, selection will always be pink damnit!

**Comment by andremiguelaa** [comment]
@innovandrew thumbs up!
