### ISSUE TITLE
Metatags and Server headers.

### ISSUE THREAD

**Issue by MechanisM** [h5bp/html5-boilerplate#971]
I see metatags X-UA-Compatible in html, why? It's already added in .htaccess(or in nginx conifg). 
Same needed for charset.
For example, part of my nginx config looks like following:

```
add_header X-UA-Compatible IE=Edge,chrome=1;
add_header charset utf-8;
```

it means that I don't need 

```
<meta charset="utf-8">
```

and

```
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
```

**Comment by Justin-Marks** [comment]
Neither google.com or youtube.com have a `<meta charset="utf-8">` or `<meta http-equiv="Content-Type" content="text/html; charset=utf-8">` tag in the head. If Google doesn't think it's necessary then I'm not using it anymore either and just use the HTTP header.

**Comment by adamralph** [comment]
Google and YouTube don't care about saving and later viewing pages offline. Also they have control of their http headers which not everyone does.

**Comment by Justin-Marks** [comment]
If that's the reason they chose to omit the charset declaration, then it means they think it's only useful for people who save pages for offline viewing. Even in those cases, the browser can usually detect the correct encoding. In the edge cases where it doesn't, at worst the user sees a funky looking page while viewing a saved page offline... oh well... I guess Google is confident enough that omitting the `<meta charset="utf-8">` won't cause any security issues at least.  Service Workers can now enable offline browsing anyway, so there's going to be no need for those people saving pages for offline browsing in the future. If you can control the HTTP header then I don't see any good reason for using `<meta charset="utf-8">`.

**Comment by adamralph** [comment]
The key point is

> If you can control the HTTP header

E.g. when using GitHub pages, you can't.

**Comment by Justin-Marks** [comment]
Yep, no dispute there.
