### ISSUE TITLE
disable user dragging on images

### ISSUE THREAD

**Issue by csicar** [h5bp/html5-boilerplate#996]
For disabling user dragging on images
Just add 

user-drag: none;
-moz-user-select: none;
 -webkit-user-drag: none;

to the standart css.
I think that helps webpages react like they should

**Comment by chadams** [comment]
here is a real world scenario. We are making a kiosk with no desktop, user is using touch and gestures for interaction. if they touch an image and drag we get a ghost image for dragging onto desktop which totally breaks the gesture interactions. On chrome -webkit-user-drag: none; totally fixes this issue, Mozilla is still broken as -moz-user-select: none;   & 	user-drag: none;  have no effect.

**Comment by patrickkettner** [comment]
That is a great reason to disable drag n drop on _your_ site, not every site using h5bp
